### ISSUE TITLE
Manually added skill events render as the previous day in the User Performed Skills table in the dashboard

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1000]
This is likely an issue with timezone formatting in the dashboard display.

Steps to reproduce:
1. Manually add a skill event via Project->Subject->Skill->Add Event
2. Browse to the Skill -> Users -> Performed Skills for the user the event was added for
3. Note that the Performed On value displayed for the skill event is for the day previous to what was selected in step 1

It appears that the entry in the user_performed_skill table matches the date specified in step 1, and deleting the event through the dashboard succeeds, so more than likely it's a function of improper timezone handling of that column in the dashboard.

**Comment by mosefer** [comment]
only shows up if event is added for day prior to "today"

**Comment by mosefer** [comment]
PR: #1036

**Comment by mosefer** [comment]
Note that this doesn't show up in the automated tests as they are run in UTC, this is evident in non-utc timezones.

**Comment by rmmayo** [comment]
:+1:
