### ISSUE TITLE
Skill group partial requirement count is wrong when copying skills

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1003]
Skill group partial requirement count is wrong when copying skills
- create new group
- add skill to the group
- copy the skill
- change required to 1 out of 2
- notice that required says "1 out of 1"

![image](https://user-images.githubusercontent.com/51749745/144627301-ee363e95-629a-48e6-9b91-02f7e1741a13.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1006

**Comment by rmmayo** [comment]
:+1:
