### ISSUE TITLE
Invite-only dashboard Progress and Ranking access

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1018]
- project Administrator emails project-specific registration code
- registration code gives ability to view Progress and Ranking (P&R) pages for that project
- optional mode to restrict access to the dashboard altogether unless user has project-level registration code
- registration code expires
- optional mode where users that created account with P&R mode can only see Progress and Ranking portion of the dashboard

Relates to https://github.com/NationalSecurityAgency/skills-service/issues/1017

**Comment by mosefer** [comment]
PR: #1520

**Comment by rmmayo** [comment]
:+1:
