### ISSUE TITLE
Editing a skill decrements # of skills in the subject's stats

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1019]
- create a skill  and validate that the subject card on subject and subjects pages show correct # of skills (should be 1)
- edit the skill - number of skills is now 0 instead of 1

Note: doesn't look like group's child skills exhibit this bug

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1020

**Comment by mosefer** [comment]
:+1:
