### ISSUE TITLE
Crossing the max # of skills per subject produces a HTTP 400 and is not shown in the ui 

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1033]
When creating a new group, if the max number of skills for a subject has been reached, the group creation fails and the user is displayed an incorrect error page that states: "Resource Not Found, Skill [test1Group] doesn't exist"

**Comment by sudo-may** [comment]
A good way to handle the issue is to disable the create button when the configured threshold is reached. In addition a warning should be displayed. This applies to the creation of projects, subjects, badges, groups and skills

**Comment by mosefer** [comment]
#1061, #1060, and #1062 also created

**Comment by rmmayo** [comment]
:+1:
