### ISSUE TITLE
Automatically Pin Project's for Root Admin users when they are a project administrator

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1043]
Automatically Pin projects for Root Administrator users when they have been added as a Project Administrator to a specific project.

**Comment by sudo-may** [comment]
@rmmayo also need to cover the case when a user is added as root admin by another root admin; in this case must iterate over all of the projects that the user already admin for and "pin" those projects

**Comment by sudo-may** [comment]
:+1:
