### ISSUE TITLE
Add achievement status column to Badge Users table

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1047]
Add an Achieved column to the Users table for a Badge. Currently Users shows users who have any amount of progress on the badge but there is no indication of whether a user in that table has achieved the badge. As of today, it is necessary to navigate to a separate metrics view to identify users who have fully achieved a Badge.

**Comment by dwalizer** [comment]
Progress indicator is already showing progress towards badge, so this issue is OBE.
