### ISSUE TITLE
correct that so that the achievement is awarded on the date of the last qualifying event

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#106]
Currently we use row's ``created_date``; if the events are replied from the past then achievement date is not equal to creation date. There is also a precedent set via ``user_performed_skill.performed_on``. 

Please also revisit achievement date in client-display as well.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/112

**Comment by rmmayo** [comment]
@dimay - badge and global badge summaries are using the createdDate and not the achievedOn date.  I'm pretty sure you want that to use achievedOn date?
