### ISSUE TITLE
Catalog imported skills fail to show self-reported approval request information

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1068]
Catalog imported skills fail to show self-reported approval request information as well as to disable 'I did it' button. To replicate navigate to an imported self-reported with approval skill then click 'I did it'. Refresh the page.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1071

**Comment by mosefer** [comment]
:+1:
