### ISSUE TITLE
Select skills to import from the catalog, then change pages and the selected skills are not imported

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1069]
When importing skills from the catalog, if you have multiple pages of skills that can be imported...

1. select some skills (or all) on page 1:
![image](https://user-images.githubusercontent.com/47030042/149950963-1bd1b454-6be8-4d13-85ca-4b5f59e8567f.png)

2. change pages, the `Import` button is still enabled and the number of skills selected in step 1 (2) is still listed:
![image](https://user-images.githubusercontent.com/47030042/149951591-725cce0c-d2f1-4157-93c0-011bfe9fbf5f.png)

3. Click `Import`, no skills are actually imported.

The previously selected skills should carry over when changing pages (this solution is preferred since this would be ideal for importing more skills that fit on a single page),  or the selected skills from the previous page should be cleared and the `Import` button disabled.

**Comment by mosefer** [comment]
work was done on the catalog dev branch

**Comment by sudo-may** [comment]
:+1:
