### ISSUE TITLE
Icon Selector is broken

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#110]
Edit Subject -> Click Icon

Icon selector launches but Font Awesome and Material icon tabs are empty. A variety of TypeErrors are spewed to the console.

**Comment by rmmayo** [comment]
appears to be related to vue-virtual-scroll-list which was updated from 1.4.2 to 2.3.1 in 3d490dfeb1afa63d9de4c08e4c7e31834fd66f95

**Comment by mosefer** [comment]
This ticket blocks #96

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/118
