### ISSUE TITLE
Keyboard navigation of My Usage chart inconsistent

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1103]
Navigating the My Usage by keyboard, it is not possible to select the 30 days/6 months/1 year time selectors via keyboard navigation. Navigation of the selected project tags (presuming use of My Usage from the Progress And Ranking page) also have the wrong tab order. If the page is loaded on a page refresh the tab order appears to be Project Selection Tags -> Home Icon -> User Menu -> Help Menu -> Breadcrumb bar -> Project selection drop down (NOT existing tags) -> Service Desk -> Email Us. 

If navigated to from the Progress And Rankings page the tab order is Service Desk -> Email Us -> Location Bar -> Existing Project Tag X button (N number of times) -> Home Icon -> User Menu -> Help Menu -> Breadcrumb bar -> Project selection drop down -> Service Desk...etc

**Comment by mosefer** [comment]
inconsistent tab order is due in part to the vue-multiselect library setting a tabindex of 1 to certain items, creating another ticket to migrate from vue-multiselect to something else as vue-multiselect does not handle accessibility issues well.

**Comment by rmmayo** [comment]
:+1:
