### ISSUE TITLE
client-display does not support keyboard navigation

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1106]
The majority of elements within the client-display are not tab navigable - on the initial display only the powered by skilltree link and the Point History zoom button are keyboard navigable. When using the mouse to navigate into a subject, some items are navigable (the search and filter button) but most are not, including the skill details button and individual skills. My Badges does support navigation although the order of navigation is incorrect if the page is not loaded directly/refreshed.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1407
