### ISSUE TITLE
Utilize local storage for an extra level of resiliency to preserve skill/badge/project/subject attributes (ex. description)

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1129]
Add an extra level of protection when users spend time to create a **new** skill/badge/project/subject attributes followed by the failure to save those changes (due to the networking hiccup, infrastructure instability or a SkillTree bug). Prevent entered information from being lost in the event of unexpected failures. 

- Store attributes in local storage as they are entered
- clear local storage when information is saved or modal is closed by the user
- (optional): when closing a modal warn users if the values changed since the modal was opened 
- keep the information in local storage unless modal is closed by the user which addresses application errors, networking hiccups, accidental refresh, computer restarts, etc... 
- alert the user if the information is restored

**Comment by rmmayo** [comment]
:+1:
