### ISSUE TITLE
Routing to new components does not alert screen reader users of changes

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1165]
Routing to new components does not alert screen reader users to changes in content. See https://marcus.io/blog/improved-accessible-routing-vuejs for a fairly thorough discussion of possible solutions in Vue.

**Comment by mosefer** [comment]
After discussions of potential solutions, addressed focus issues when routing to a new route for this ticket. Route change announcement was addressed as part of a previous ticket.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1385

**Comment by rmmayo** [comment]
:+1:
