### ISSUE TITLE
The collapse/expand navigation menu button needs alt text/aria label

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1168]
The collapse/expand navigation menu button needs an aria-label or alt-text on the icon as currently only hover text explains what the button does and it's current state, which is not available to keyboard users/screen reader users.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1344

**Comment by rmmayo** [comment]
:+1:
