### ISSUE TITLE
The New Project button needs a better description for accessibility users

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1177]
The New Project button needs to include an aria-label or similar solution for screen reader/accessibility users. Otherwise context is unclear as it is described just as "Project" without any indication that the button is for the purpose of creating a _new_ Project.

**Comment by rmmayo** [comment]
addressed in #1178 (see https://github.com/NationalSecurityAgency/skills-service/commit/06b83636a398dbc0682bfcdd7dcc4e11992754f1)

**Comment by sudo-may** [comment]
:+1:
