### ISSUE TITLE
Check the point system and warn users when finalizing skills catalog if imported points are outside of the exiting point scheme

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1200]
- scan the point system and warn that imported skills don't match the points system
- when finalized is clicked check whether points for imported skills are not too large / small then enhance the modal with a warning

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1325

**Comment by rmmayo** [comment]
:+1:
