### ISSUE TITLE
Set focus after Import and Export modals are closed

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1205]
On the skills page:
- return focus to the "Import" button after the modal that initiated by the "Import" button is closed 
- return focus to the "Clear" button after the modal initiated by the "Action" button is cancelled
- return focus to the "Select All" button after the modal initiated by the "Action" button completed its action (this is because the "Action" button is disabled and all of the selections are cleared)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1218

**Comment by rmmayo** [comment]
:+1:
