### ISSUE TITLE
Data tables don't include title elements

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1214]
Data tables don't include title elements to alert screen readers to what the data table contains. One alternative would be to include a caption element with the sr-only class to include appropriate description of the table contents for screen reader users. This applies to the Skills, Badges, Levels, Users, Issues, and Access tables as of now.

**Comment by rmmayo** [comment]
PR: #1425

**Comment by mosefer** [comment]
:+1:
