### ISSUE TITLE
Project Users page does not correctly count users of imported skills

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1225]
The project users page does not correctly account for users of skills imported from the catalog. An extreme example of this can be seen when a project consists _only_ of skills imported from the catalog. In this case the Project Users page will return no users whatsoever while subject users pages will return the appropriate users.

**Comment by rmmayo** [comment]
PR: #1231

**Comment by sudo-may** [comment]
:+1:
