### ISSUE TITLE
Several Inception/dashboard skills are not awarded

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1229]
- Visit Subject Metrics
- Visit Badge Metrics (does not exist anymore)
- Preview Client Display for Project
- Visit User Metrics (does not exist anymore)

**Comment by rmmayo** [comment]
if Inception skills are removed from the code, then they should also be removed from the database on startup

**Comment by sudo-may** [comment]
:+1:
