### ISSUE TITLE
Do not allow enabling badges without any skills

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#125]
Badges should not be allowed to be enabled if they do not contain any skills.  Likewise, once a badge is enabled, you should not be allowed to remove the last skill from the badge.

**Comment by rmmayo** [comment]
@cjmoses - I created a project badge, then added a skill and enabled it.  Then, I went to remove the skill from the badge and got a 400 error

**Comment by rmmayo** [comment]
![image](https://user-images.githubusercontent.com/47030042/98876902-42feab00-244d-11eb-90da-e892cc2f139e.png)

**Comment by mosefer** [comment]
@rmmayo - conversations with @sudo-may resulted in this ticket evolving to drop the "prevent deletion of last skill on badge" portion of the ticket. It looks like a server side check is still in place, I'll remove that. The only real capability this ticket should enforce, is preventing enabling of an empty badge.

**Comment by rmmayo** [comment]
verified!
