### ISSUE TITLE
Polling for finalization state returns `net::ERR_CONNECTION_CLOSED 200` with no data eventually

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1254]
![image](https://user-images.githubusercontent.com/47030042/161323060-12dfe230-0b80-4bbd-a2b6-80c127bc7252.png)
![image](https://user-images.githubusercontent.com/47030042/161323121-f2c6b3b9-1aae-422c-af8c-3e1b319845c4.png)

**Comment by rmmayo** [comment]
PR: #1258

**Comment by sudo-may** [comment]
:+1:
