### ISSUE TITLE
Improve dashboard's usability of 'Help Url'

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#126]
``Help Url`` is applicable when creating or editing subject, badges or skills.
- if root url is configured for that project then display it before the input box
  - add text to explain that entering help url with a protocol (http/https) will override the root url
  - when root url is overridden visually indicate what is happening (red x? / overlay?)
  - once value is saved display root help url so user knows where the url actually will lead
- add validation to help url input box

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/991

**Comment by rmmayo** [comment]
after setting custom hrlp url dor the project, I am unable to create a new skill:

**Comment by rmmayo** [comment]
Update: 

It does pass validation if I add a leading `/` but I don't think the user should have to when setting the `Help URL/Path` is set.  
![image](https://user-images.githubusercontent.com/47030042/144458274-edbe9b08-28ec-4a6d-a610-a147e3f09eb0.png)


Maybe add the leading `/` if the trailing `/` is not present in the `Root Help Url` (which it is in this case it is though), or force the trailing `/` when setting the `Root Help Url`?

**Comment by rmmayo** [comment]
:+1:

added separate ticket for this issue: #998
