### ISSUE TITLE
Removing an original skill does not properly update project and user points for its imported counterparts

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1289]
- Create 2 projects; project A export and project B import
- report few events for the original skill
- verify they propagated
- remove an original skill 

The issue is in the import project:
- overall project and subject points are not updated
- users' points are not updated

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1291

**Comment by mosefer** [comment]
:+1:
