### ISSUE TITLE
Project Users view includes users of unfinalized imported skills in the total rows count

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1293]
The Users for for a Project in the dashboard includes in the Total Rows count, users of imported skills that have not yet been finalized (those users are not included as actual data rows though, only in the total count). This results in paging controls showing up when there are less than one full page of users. To reproduce this issue, create a two projects, export skills from Project 1 and add several events for different users. Import skills from Project 1 into Project 2 without finalizing the import, note that the Total Rows count for the Project Users view includes the users from the un-finalized imports. This only impacts the Project Users view and does not impact Subject Users.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1305

**Comment by mosefer** [comment]
:+1:
