### ISSUE TITLE
Very long skill names break the rendering of the "Import Skills from the Catalog" dialog

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1320]
Creating a skill name that is a long unbroken string of characters breaks rendering on the Import Skills from the Catalog dialog when the screen/browser size is reduced.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1323

**Comment by rmmayo** [comment]
:+1:
