### ISSUE TITLE
Long skill ids with unbroken strings of characters break rendering on self-report view in the dashboard

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1321]
Create a skill that is self reportable and requires approval. Give it an id that is a very long string of characters with no spaces. 

In the self-report view for a Project, the long id breaks the rendering of the the requested approvals table, also likely in the approval history table.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1322

**Comment by rmmayo** [comment]
:+1:
