### ISSUE TITLE
Project Id in the dashboard's project admin URL param is case insensitive

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1324]
If you change the case of the projectId path param in the dashboard, it will load the project but no subjects.

steps to recreate 

1. create a test project with subjects
2. navigate to the admin page for that project
3. change the case of one or more of the letters in the `projectId` url param and load that page (e.g, change `/administrator/projects/MyProject/` to `/administrator/projects/myproject`

since `myproject` does not exisit it should load the "Resouce Not Found" page

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1327

**Comment by rmmayo** [comment]
:+1:
