### ISSUE TITLE
Add data migration for simplified skill groups with optional skills

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1356]
Add data migration now that skill groups no longer contribute to `user_points`, and all child skills contribute to skill/subject/project `total_points` regardless of `num_skills_required`

See #1346 

Data Migration
 - fix skill_definition points; fix group's total points; update project and subject points 
 - remove user_points row for groups
 - fix user_points for subjects and projects for any project that has optional skills enabled
 -  enable all groups and their child skills

**Comment by sudo-may** [comment]
testing this ticket generated https://github.com/NationalSecurityAgency/skills-service/issues/1378

**Comment by sudo-may** [comment]
:+1:

**Comment by rmmayo** [comment]
PR: #1366
