### ISSUE TITLE
Add the ability to make the comment/justification for a self-report skill required

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1369]

**Comment by rmmayo** [comment]
PR: #1506

**Comment by mosefer** [comment]
It looks like there isn't sufficient aria labeling for the Justification required checkbox is not sufficient for screenreader usage. Selecting/tab navigating to the checkbox with a screen reader enabled only notifies the user of "checkbox checked/unchecked" without the context of what the checkbox is for (Self Reporting enabled/disabled checkbox for example clearly describes what the checkbox purpose is for the screenreader).

**Comment by rmmayo** [comment]
PR: #1514

**Comment by mosefer** [comment]
:+1:
