### ISSUE TITLE
Point History chart does not work for skill groups child 

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1389]

**Comment by mosefer** [comment]
could not reproduce, steps attempted:

1. Create Project with Group Skill with multiple children.
2. Assign two events, one for today and today-n where n > 1 for current user, to a single group child skill
3. Ensure that current user has no other skill events in the project
4. Preview client-display 
5. Point History chart was displayed as expected, unlocked

1. Create Project with Group Skill with multiple children
2. Assign two events, one for today and today-n where n > 1 for current user, to a single group child skill
3. Export group child skill to catalog
4. Create 2nd project
5. Import child group skill from step 1.
6. Ensure that no other events exist in either Project 1 or Project 2 for current user beyond events added to Group Child Skill in step 2.
7. Point History chart was displayed as expected, unlocked

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1393

**Comment by sudo-may** [comment]
:+1:
