### ISSUE TITLE
Self Reporting from the dashboard reports the skill for the dashboard user instead of the skills-display user being viewed 

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1390]
This occurs in pki auth mode, possibly in others.   The correct `userId` param is sent in the request payload, but the `user_id` column for the `user_points` entry is for the currently logged in dashboard user.

**Comment by sudo-may** [comment]
acknowledging approval rejection has the same issue: 
![image](https://user-images.githubusercontent.com/51749745/173240566-6d0db090-d89b-42de-8c3a-d4aaa07795fd.png)

**Comment by sudo-may** [comment]
:+1: 
while testing found this issue: https://github.com/NationalSecurityAgency/skills-service/issues/1409
