### ISSUE TITLE
Skills Display: ``Points Today`` are wrong for imported skill on skill's page but are correct on the subject page

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1395]
First screenshot is from the subject page, 2nd after drilling down into skill page:
![image](https://user-images.githubusercontent.com/51749745/173241087-bb41a7e5-15bf-457f-a689-efa3828d1a88.png)
vs.
![image](https://user-images.githubusercontent.com/51749745/173241109-0196f991-208c-474d-b19f-bcea49eabfc6.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1399

**Comment by mosefer** [comment]
:+1:
