### ISSUE TITLE
Remove unnecessary validation for group's partial requirement

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1398]
starting with 1.10.0 there is no need to enforce the Point Increment and Point Occurrences attributes matching for all the child skills
- remove UI validation and any associated validation endpoints
![image](https://user-images.githubusercontent.com/51749745/173370799-27b13720-8e87-4ddb-827a-06ab6e332233.png)
- remove validation when editing a child skill for a group with the partial skill req.
![image](https://user-images.githubusercontent.com/51749745/173370660-16ed7707-fc08-4db3-a558-09d751c54193.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1400

**Comment by rmmayo** [comment]
:+1:
