### ISSUE TITLE
Acknowledging an approval rejection from the **imported** skill causes an error

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1409]
![image](https://user-images.githubusercontent.com/51749745/173579366-c0637757-de01-4661-880a-93fc2ead46e7.png)

![image](https://user-images.githubusercontent.com/51749745/173579257-e23e7fb1-111f-4bcc-8bf1-bfd3022cfff7.png)

**Comment by rmmayo** [comment]
:+1:
