### ISSUE TITLE
Add ability to re-use skills within the same project

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1412]
- add ability to copy a read-only version of a skill into a different subject or group (copy-by-reference)
- one idea is to enhance the copy skill button, another idea is to add another button next to the copy button

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1469

**Comment by mosefer** [comment]
:+1:
