### ISSUE TITLE
Unpin button missing from projects table for root user

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1422]
If the root user pins enough projects in the projects view to present as a table (10 or more), then the inline "Unpin" button is missing from the table.  The user can however still select the over all Pin dialog 
![image](https://user-images.githubusercontent.com/47030042/175313005-35a2e005-029e-4ec3-a86f-b3b407e1bdce.png)
 in order to unpin a project.

![image](https://user-images.githubusercontent.com/47030042/175312861-f7c52c64-9f26-4fad-9e35-1f1ee2c5a340.png)

**Comment by rmmayo** [comment]
PR: #1599

**Comment by mosefer** [comment]
:+1:
