### ISSUE TITLE
Overhaul custom icon uploader

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#1443]
The custom icon uploader has a few issues, notably that it doesn't validate the size of the icons being uploaded, allowing icons greater than 100x100, it has issues with allowing a user to select an already uploaded icon (it seems to just have a blank icon instead) and the potential for a user to mistakenly remove icons tied to other badges.  The component could use some TLC to address these issues and improve functionality / usability.

**Comment by sudo-may** [comment]
might make #256 OBE

**Comment by sudo-may** [comment]
OBE
