### ISSUE TITLE
AzureAD Unauthorized 

### ISSUE THREAD

**Issue by dsmhood** [NationalSecurityAgency/skills-service#1448]
I'm not sure if this is a software bug or if I'm just misconfiguring this feature. 

I'm trying to setup the AzureAD integration with SkillTree. When I attempt to authenticate with a user, it redirects to AzureAD and AzureAD authenticates the user, then AzureAD redirects back to SkillTree and SkillTree gives me a HTTP/401 (https://host/login/oauth2/code/azure?code=....). 

I've got the following as relevant configuration:
spring.security.oauth2.client.registration.azure.client-id=72XXXX
spring.security.oauth2.client.registration.azure.client-secret="OtXXXXX"
spring.security.oauth2.client.registration.azure.redirect-uri="https://host/{action}/oauth2/code/{registrationId}" 
spring.security.oauth2.client.registration.azure.iconClass=fab fa-microsoft 
spring.security.oauth2.client.registration.azure.scope=openid,profile,email 
spring.security.oauth2.client.registration.azure.authorization-grant-type=authorization_code 
spring.security.oauth2.client.registration.azure.client-name=Azure 
spring.security.oauth2.client.registration.azure.provider=azuread 
spring.security.oauth2.client.provider.azuread.authorization-uri=https://login.microsoftonline.com/mydomain.com/oauth2/v2.0/authorize 
spring.security.oauth2.client.provider.azuread.token-uri=https://login.microsoftonline.com/mydomain.com/oauth2/v2.0/token 
spring.security.oauth2.client.provider.azuread.user-info-uri=https://graph.microsoft.com/oidc/userinfo 
spring.security.oauth2.client.provider.azuread.jwk-set-uri=https://login.microsoftonline.com/mydomain.com/discovery/keys 

I've setup the configuration in AzureAD (including a reply URL of "https://host/login/oauth2/code/azure".  

What am I doing wrong? Or is this a software issue?

**Comment by rmmayo** [comment]
Hello @dsmhood - sorry to hear you are having issues with the AzureAD configuration.  Users have successfully enabled Azure AD with SkillTree in the past so there is likely a configuration or environment issue you are running into.

Can you please try adding the following property: `
spring.security.oauth2.client.provider.azuread.userNameAttribute=sub`


Also, if you can provide us with the relevant logs from the skills-service SpringBoot application that could help us figure out what is happening.

**Comment by Matthijsy** [comment]
I am actually experiencing the same issue. I have the same kind of configuration as above, adding the `userNameAttribute` as suggested above did not resolve it. When you are returned to SkillTree from AzureAD there is a 401 - Unauthorized page, without any logging in the terminal.

These are the steps I take:
1. Startup SkillTree
2. Go to `localhost:8080`
3. Click on `Login via Azure`
4. Authenticate yourself within Azure
5. You are redirected back to `http://localhost:8080/login/oauth2/code/azure`, which then shows a 401, as shown below:

<img width="1440" alt="Screenshot 2023-05-31 at 21 54 47" src="https://github.com/NationalSecurityAgency/skills-service/assets/5302372/f2f99e27-5f55-45cd-a60f-ddcecae2fa62">

These are all logs after the moment the app is initialized:

```
app_1  | 2023-05-31T19:55:48.499Z  INFO 48 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
app_1  | 2023-05-31T19:55:48.500Z  INFO 48 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
app_1  | 2023-05-31T19:55:48.507Z  INFO 48 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 6 ms
app_1  | 2023-05-31T19:55:50.809Z  INFO 48 --- [nio-8080-exec-2] skills.auth.UserInfoService              : Unexpected/Unauthenticated princial [anonymousUser]
app_1  | 2023-05-31T19:55:51.027Z  INFO 48 --- [nio-8080-exec-3] skills.auth.UserInfoService              : Unexpected/Unauthenticated princial [anonymousUser]
```

The logs about `Unexpected/Unauthenticated princial` are already logged before clicking the `Login via Azure` button, so they seem not to be related. 

Anyone that has this working that can help me out?

**Comment by Matthijsy** [comment]
For people finding this issue in the future, the fix is removing the quotes around your client secret. 

So this is incorrect:
```
spring.security.oauth2.client.registration.azure.client-secret="OtXXXXX"
```

The correct config is
```
spring.security.oauth2.client.registration.azure.client-secret=OtXXXXX
```
