### ISSUE TITLE
Visiting Page metrics tracking reports incorrect hostname

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1458]
Because skills-display is being served from the SkillTree web server within an iframe, the hostname being reported in page visit metrics (#1381) is the SkillTree server hostname instead of the client app's web server.

see https://stackoverflow.com/questions/3420004/access-parent-url-from-iframe for ideas on how to fix

**Comment by rmmayo** [comment]
PR: #1463

**Comment by sudo-may** [comment]
:+1:
