### ISSUE TITLE
Show Primary Name when set in leader board display in non-pki auth mode

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1476]
if the `Primary Name` field is set, use it in the Leaderboard display in non-pki mode (currently it is only used in pki mode)

**Comment by rmmayo** [comment]
https://github.com/NationalSecurityAgency/skills-service/pull/1480/commits/a5b35f86f34956b01cced0ddd5ef79797aa5c8d0

**Comment by rmmayo** [comment]
PR: #1480

**Comment by mosefer** [comment]
:+1:
