### ISSUE TITLE
Extract from email to configuration

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#15]
Extract the from email used in EmailSendingService to either system properties or configuration via the user interface available to the Root User account.

**Comment by rmmayo** [comment]
@cjmoses - the from email address setting works, but it does not validate that the value is a valid email address.   I forgot the @ sign and it let me save it.  seemed to work when validating the email was sent to MailHog mock smtp server

**Comment by mosefer** [comment]
@rmmayo - validation was addressed in #37

**Comment by rmmayo** [comment]
:+1:
