### ISSUE TITLE
total subject points are incorrect for groups with optional skills

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1500]
To recreate:

1. - create project with one subject, then under that subject:
    - create 1 regular skill (100 points, 1 increment, self report - honor system)
    - create 1 group, requiring 3 of 4 child skills, all of skills (100 points, 1 increment, self report - honor system)

2. - go to Preview for the project, under the subject complete (self report) all skills  

3. - skills-display reports regular skill and group and all child skills complete, but 400 out of 500 points

Note: the regular skills and/or point totals, self report, etc. may or may not be necessary but those were the steps taken initially to create the bug.

Total points within Subject: 
![image](https://user-images.githubusercontent.com/47030042/180063097-0f554b88-0ffb-4c30-a4ba-9dcb4e05a988.png)

Total points for subject at project level (show correctly):
![image](https://user-images.githubusercontent.com/47030042/180063266-74b1aee3-017f-4478-acac-3df9da51d501.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1504

**Comment by rmmayo** [comment]
:+1:
