### ISSUE TITLE
number of points displayed in stat cards for reused skills is not formatted

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1501]
number of points displayed in stat cards for reused skills is not formatted:

![image](https://user-images.githubusercontent.com/51749745/180518172-18e38d4b-224a-4099-a217-9077517661ca.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1505

**Comment by rmmayo** [comment]
:+1:
