### ISSUE TITLE
Add Event navigation is disabled when navigation from the reused skill to the original skill

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1502]
- reuse a skill - make sure that subject of the reused skill does not have enough points
- from the reused skill navigate to the original skill
![image](https://user-images.githubusercontent.com/51749745/180784313-4f799393-c0a2-4152-97b0-e1dabb204563.png)
- ``Add Event`` is disabled due to the insufficient points even though the subject where the original skill is has enough points to report skill events
![image](https://user-images.githubusercontent.com/51749745/180784428-93584f13-2240-45d0-84f0-9b1ce2926ac7.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1503

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1507

**Comment by rmmayo** [comment]
:+1:
