### ISSUE TITLE
Develop User Tag Metric page

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1512]
- Values in User Tags are clickable which will lead to User Tag Metric Page
- User Tag Metrics page
  - will depict number of users that achieved each level
  - show user table for users that have that tag; each row will show user's progress (maybe similar to how leaderboard presents it) and will allow to drill down
- Please note that User Tag charts are not always enabled

**Comment by rmmayo** [comment]
PR: #1611

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1624

**Comment by sudo-may** [comment]
:+1:
