### ISSUE TITLE
Navigation to skill's dependencies doesn't use the correct subject in the URL

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1518]
1. Create 2 subjects and 2 skills - 1 per subject
2. Add 1 skill to depend on the other
3. Navigate to the parent's dependency page and click "Manage" on its child/dep skill

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1530

**Comment by dwalizer** [comment]
:+1:
