### ISSUE TITLE
Moving all the skills from one subject to another doesn't remove users's subject level achievement from the original subject

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1522]
- subject had many users with subject level achievements
- skills were moved into another subject
- original subject metrics still displayed user achievements:
![image](https://user-images.githubusercontent.com/51749745/182378524-2a9c1a44-2dc2-404d-9d48-62f349860ac4.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1527

**Comment by mosefer** [comment]
:+1:
