### ISSUE TITLE
Skills Display: Add "last viewed" visual indicator next to the skill on the subject page; scroll to the skill when navigating back from the Skill Overview Page

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1524]
overall issue is ``view subject -> click skill, read about skill -> go back -> where was I?``

- Add "last viewed" visual indicator next to the skill on the subject page
- scroll to the last viewed skill when navigating back from the Skill Overview Page

**Comment by dwalizer** [comment]
PR #1666

**Comment by dwalizer** [comment]
PR #1673

**Comment by sudo-may** [comment]
:+1:
