### ISSUE TITLE
Add ability to copy project's training profile

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1529]

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1541

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1542

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1545

**Comment by rmmayo** [comment]
👍
