### ISSUE TITLE
Project Custom Label not showing when viewing skills display from dashboard (Progress and Rankings)

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1533]
![image](https://user-images.githubusercontent.com/47030042/183117357-c48b26b2-7770-472b-9158-e84a1f63802a.png)

**Comment by rmmayo** [comment]
committed under wrong ticket by accident: [198161d](https://github.com/NationalSecurityAgency/skills-service/pull/1534/commits/198161dec63d80b614b5af688017993713cdce25)

**Comment by rmmayo** [comment]
PR: #1534

**Comment by rmmayo** [comment]
PR: #1540

**Comment by mosefer** [comment]
:+1:
