### ISSUE TITLE
Dismissing the Pin Projects dialog via ESC then loading the new Project dialog causes both to display

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#154]
Dismissing the Pin Projects dialog via the ESC key then launching the new Project Dialog causes the new Project dialog to render with the Pin Projects dialog visible beneath it.

![image](https://user-images.githubusercontent.com/61209506/98560999-5e638d80-2276-11eb-83b7-a454b9d4a5b6.png)

**Comment by mosefer** [comment]
Additional note that it appears that if the Pin dialog is closed via the ESC key, the dialog cannot be relaunched by the Pin button until it has been closed via cancel or X (by launching the Project dialog to expose the hidden Pin dialog).

**Comment by rmmayo** [comment]
PR: #157
