### ISSUE TITLE
Max projects per user should NOT apply to the root role

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1551]
root users can pin/unpin projects so it's perfectly fine to allow unlimited number of projects; currently when root users reach maximum number of subjects UI validation fails to gracefully validate and emits an error page

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1574

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1582

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1586

**Comment by mosefer** [comment]
:+1:
