### ISSUE TITLE
Wrong # of skills required after moving child skills out of a group 

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1556]
Create a group with multiple skills, change the amount required so that some skills are options (2 out of 3), then move all the skills to another group - the group will be empty, but it will say "Required: 2 out 0 skills".  This should be changed to the default for an empty group "ALL SKILLS" (-1)

![image](https://user-images.githubusercontent.com/47030042/184165692-e7684a00-663e-49b3-b4e1-421f3cc298d3.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1561

**Comment by rmmayo** [comment]
:+1:
