### ISSUE TITLE
AccessSettings.vue should use the project details already in vuex

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1558]
AccessSettings.vue calls ProjectService.getProjectDetails in mount for little apparent purpose. The component should use the value already populated in vuex as opposed to issuing an unnecessary (and at times slow) query.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1573

**Comment by dwalizer** [comment]
:+1:
