### ISSUE TITLE
Last Reported Skill date can be slow to load

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1559]
If a Project has many users and an extensive history, the last reported skill date can be slow to load. Currently that is included as part of the project details query and can introduce unnecessary latency. Consider extracting the last reported skill date into it's own endpoint.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1571

**Comment by sudo-may** [comment]
pr: https://github.com/NationalSecurityAgency/skills-service/pull/1581

**Comment by dwalizer** [comment]
:+1:
