### ISSUE TITLE
Add execution times to the cypress logs so the tests can be correlated to skills-service logs

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1575]

**Comment by sudo-may** [comment]
Need to first upgrade cypress to at least version 8.2.0 as that's when support for ``Cypress.currentTest.title`` was added

https://docs.cypress.io/api/cypress-api/currenttest#Syntax

also here is a helpful article: https://glebbahmutov.com/blog/cypress-timestamps/

**Comment by sudo-may** [comment]
depends on #1576

**Comment by rmmayo** [comment]
:+1:
