### ISSUE TITLE
Ability to copy Invite URL for discoverable projects

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1578]
If a project is configured with the Visibility of "Discoverable on Progress & Rankings" then:
- Display ``Copy Invite URL`` button (next to the ``Preview`` button?)
- Invite URL takes user to the project AND adds project to the Progress & Ranking page

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1593

**Comment by mosefer** [comment]
:+1:
