### ISSUE TITLE
[Docker] Change base image for docker container: openjdk is being deprecated

### ISSUE THREAD

**Issue by antonionardella** [NationalSecurityAgency/skills-service#1584]
Hello here!

According to the docker hub, the [openjdk](https://hub.docker.com/_/openjdk) container is being deprecated completely
![image](https://user-images.githubusercontent.com/7383572/185896056-d5ac28b1-1857-49a6-8534-c768f1726f2e.png)

See also https://github.com/docker-library/openjdk/issues/505

The docker build of skill-services is based on the [openjdk:18-jdk-slim-bullseye](https://github.com/NationalSecurityAgency/skills-service/blob/fca9e421218a309ea3cbfd0fa210cc1276fc7de4/docker/Dockerfile#L1) image

The discussion will probably be around which image to use as base from now on

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1623

**Comment by mosefer** [comment]
@antonionardella - the skills-service docker build has been updated to use eclipse-temurin. Thanks!
