### ISSUE TITLE
User is forwarded to the "admin" dashboard when clicked on the logo

### ISSUE THREAD

**Issue by antonionardella** [NationalSecurityAgency/skills-service#1585]
Hello here!

I am experimenting with skilltree to figure out how it works and to plan it's implementation in our community.

My setup is a self hosted docker container behind a traefik proxy.

I have now set up a test project of my own and I can see the project dashboard at a specific link:

`https://sub.example.org/progress-and-rankings/projects/ProjectName`

For a user to access the link they are required to sign up.
After the user registers they can access the project again.

Now if the user clicks on the logo on the top left they are forwarded to the root domain `https://sub.example.org/` which is automatically forwarding to the admin dashboard at `https://sub.example.org/administrator`
Where the `user` can now set up a project of their own.

![image](https://user-images.githubusercontent.com/7383572/185938797-0811656e-7a2d-4df4-a345-411b7a2dcbdb.png)

Not sure if this is the expected behavior for a `user` which is neither an admin, nor a supervisor

**Comment by mosefer** [comment]
@antonionardella - thanks for your interest in SkillTree! The behavior you describe is the intended functionality, however, the _default_ landing page for a user can be configured via a system property [skills.config.ui.defaultLandingPage](https://skilltreeplatform.dev/dashboard/install-guide/config.html#progress-and-ranking-views). The default value for that setting is admin which results in the behavior that you are describing. You can update the system configuration property as described in the link and that will result in the logo link taking users to the progress and ranking view.

**Comment by antonionardella** [comment]
Thank you very much for your prompt answer!
I will look into that.
