### ISSUE TITLE
GitHub OAuth setup

### ISSUE THREAD

**Issue by antonionardella** [NationalSecurityAgency/skills-service#1587]
Hello,

I am trying to set up OAuth with GitHub following [these instructions](https://skilltreeplatform.dev/dashboard/install-guide/config.html#oauth-support-pass-auth-mode-only)

_Note_: The Skilltree instance is behind a [traefik.io](https://traefik.io/traefik/) proxy which handles the routing and the SSL certificates.

I set up the OAuth App on GitHub like this:
![image](https://user-images.githubusercontent.com/7383572/186117036-1d127f41-f955-4503-8233-089ad6de8554.png)

And the Skilltree settings like this in my `docker-compose.yml`
![image](https://user-images.githubusercontent.com/7383572/186108752-8b5d93c7-2f65-4b66-bbcc-10f9f9959efb.png)

The page now shows the `Login via GitHub` button as expected
![image](https://user-images.githubusercontent.com/7383572/186117279-18a647a1-84a9-4e81-bb8b-26c6662c34c7.png)

But when I try to login now I get this error:
`https://sub.example.com/not-found?error=redirect_uri_mismatch&error_description=The%20redirect_uri%20MUST%20match%20the%20registered%20callback%20URL%20for%20this%20application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=xK2ZL7_mO8c6taIoYb1CQPNMEFm_oYuLBPyWhoMk1pw%3D`
![image](https://user-images.githubusercontent.com/7383572/186117549-a1118b76-0079-4fb5-889d-022125efdf9d.png)

Can anyone point me in the right direction?

Thanks

**Comment by rmmayo** [comment]
Hi @antonionardella - I was able to recreate the issue you are seeing.  It looks like the "Authorization callback URL" is misconfigured in your GitHub OAuth application settings.  That value should be `https://<yourhostname>/login/oauth2/code/` and **not** `https://<yourhostname>/{action}/oauth2/code/{registrationId}`.

The latter is for the `spring.security.oauth2.client.registration.github.redirectUriTemplate` property which it looks like is set correctly.

Please give that try and let us know if that works.

**Comment by antonionardella** [comment]
Thanks for your reply

I set `https://<yourhostname>/login/oauth2/code/` in GitHub
![image](https://user-images.githubusercontent.com/7383572/186910631-f7034215-6ba2-435f-853f-fe66f83569d2.png)

And what I get now is:
![image](https://user-images.githubusercontent.com/7383572/186911024-33d5384d-dfb9-4464-8460-772d66fb5e3b.png)

`https://sub.example.com/login/oauth2/code/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=NI_3sF-xZvmFWuUSzCxmdkHhHoOz3FLOyCh-Dvye92c%3D`

Which is better than before.. I suppose now that the 401 comes from the traefik proxy. Now I will look into that!

Thanks a lot for your help!

**Comment by rmmayo** [comment]
I believe the hostname and port specified in the GitHub "Authorization callback URL" and the `spring.security.oauth2.client.registration.github.redirectUriTemplate` property will need to match (eg, https://sub.example.com).  See https://docs.github.com/en/developers/apps/managing-oauth-apps/troubleshooting-authorization-request-errors#redirect-uri-mismatch for me info.

**Comment by antonionardella** [comment]
Thank you, the  "Authorization callback URL" is on port 443 so the field looks like `https://sub.example.org/login/oauth2/code`

And now I am confused by your reply since this was your last reply:

> Hi @antonionardella - I was able to recreate the issue you are seeing. It looks like the "Authorization callback URL" is misconfigured in your GitHub OAuth application settings. That value should be `https://<yourhostname>/login/oauth2/code/` and **not** `https://<yourhostname>/{action}/oauth2/code/{registrationId}`.
> 
> **The latter is for the `spring.security.oauth2.client.registration.github.redirectUriTemplate` property which it looks like is set correctly.**
> 
> Please give that try and let us know if that works.

Shall I add `https://sub.example.org/login/oauth2/code` also to `spring.security.oauth2.client.registration.github.redirectUriTemplate`?

I will try nonetheless and let you know!

Thanks

**Comment by rmmayo** [comment]
Here is an example that I have working:

![image](https://user-images.githubusercontent.com/47030042/187198126-c5e0704d-ea0a-4724-8bba-8aba239dd276.png)

`spring.security.oauth2.client.registration.github.redirectUriTemplate: 'http://localhost:8080/{action}/oauth2/code/{registrationId}'`
