### ISSUE TITLE
Indicate on Project page or via Project Issues when there are unachievable levels

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1595]
Currently, if a mistake is made in configuring project and or subject levels such that they are not achievable due to subject/project available points, warnings are displayed on the Levels pages however no indication is provided at the project or subject level so a user may remain ignorant of the mis-configuration. It would be useful to add an item to Issues or display the warning at a higher level on the Project page.

**Comment by mosefer** [comment]
PR: #1698

**Comment by mosefer** [comment]
further discussions changed the direction of this ticket to include a contact project owner link as opposed to a request access feature due to the overhead of incorporating more views to manage access requests and the use case being fairly low frequency.

**Comment by rmmayo** [comment]
:+1:
