### ISSUE TITLE
Investigate exceptions being thrown from SkillsAdminService

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1596]
It appears that there are certain circumstances which can result in an NPE, specifically SkillsAdminService.convertSkillDefToRes:698 ```res.groupName = skillsGroup.name```

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1615

could not reproduce; added debug info in case this happens again
