### ISSUE TITLE
Investigate exceptions thrown by RankingLoader

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1597]
Logs have periodic exceptions when requesting ```/api/projects/<projectId/leaderboard``` when a user is opted out, ```Leaderboard type of [tenAroundMe] is not supported for opted-out users```, RankingLoader:97. This shouldn't necessarily be possible.

**Comment by sudo-may** [comment]
the issue arises when user opens the leaderboard in browser tab #1 then in a different browser tab navigates to settings and sets opt-out to true; user then attempts to view "Ten Around Me" in the original tab #1 - error is displayed 

We could handle the error in UI but for now it was decided that the displayed error sufficiently explain the situation
