### ISSUE TITLE
Automatically assign 'supervisor' role when 'root' role is added

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#163]
Automatically assign 'supervisor' role when 'root' role is added
- during bootstrap
- when 'root' role is added to another user

when 'root' role is removed also remove 'supervisor' role

**Comment by rmmayo** [comment]
PR: #168

**Comment by mosefer** [comment]
@rmmayo - it doesn't appear that the supervisor role is granted to the user created at bootstrap.

**Comment by mosefer** [comment]
works now
