### ISSUE TITLE
Edit menu wraps on Badge card if badge name is too long

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#164]
![long_name_card_rendering _bug](https://user-images.githubusercontent.com/61209506/98821237-4702dc80-23fd-11eb-9f38-6f8abd086a02.png)

If a badge name is long enough to be ellipsed, it causes the edit menu button to be wrapped. This is likely also the case for Project/Subject/Skill cards as well.

**Comment by rmmayo** [comment]
PR: #169

**Comment by mosefer** [comment]
PR has not been merged yet. Waiting to test.

**Comment by mosefer** [comment]
confirmed:
![image](https://user-images.githubusercontent.com/61209506/99725011-7c08d200-2a82-11eb-8ee7-67e4b91e4477.png)
