### ISSUE TITLE
Custom label ``Skill Display Text`` setting is not respected on the paging control of the Skill page

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1642]
Custom label ``Skill Display Text`` setting is not respected on the paging control of the Skill page: 

![image](https://user-images.githubusercontent.com/51749745/190152042-ec9f2cff-5ab3-4c3a-ae33-2042fdd13c0f.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1647

**Comment by rmmayo** [comment]
:+1:
