### ISSUE TITLE
Format number for the "characters remaining" on the Project Contact modal

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1643]
![image](https://user-images.githubusercontent.com/51749745/190154743-7b63440d-e4ed-4661-8bc4-1dcbbf57b98c.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1669

**Comment by dwalizer** [comment]
:+1:
