### ISSUE TITLE
Dashboard users are prevented from editing or copying Skills with a version > 1

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1650]
If a user creates a skill with a version > 0, any attempt to edit that skill does not work (the save button never becomes enabled after any changes) - this is related to the maxVersion validator used on the EditSkill.vue component. It appears as if the latest skill version is only looked up in the mount() method if the dialog is being created for a new skill. In the event of an Edit or Copy, the maxVersion validator is being run with an initial value of 0 so any version number > 1 fails.

**Comment by sudo-may** [comment]
:+1:
