### ISSUE TITLE
Copying a project with a Live badge that has no Skills fails

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1651]
To reproduce, 
1. create a project with subjects and skills
2. create a badge
3. assign skills to the badge created in the previous step
4. publish the badge created in step 2
5. delete all skills assigned to the badge created in step 2, leaving the badge in a Live but empty state
6. attempt to copy the project created in step 1

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1654

**Comment by dwalizer** [comment]
:+1:
