### ISSUE TITLE
Enhance skill's "post achievement  metrics" to show user table for users that continued to utilize the feature after achieving the skill

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1668]
On the Dashboard's skill page in the ``Post Achievement Metrics`` section implement a new table that will display users that achieved this skill
- Potential table title: ``Users that Achieved this Skill``
- Add ability to toggle between users that "Continued Using" vs. "Stopped Using"
  -  default to "Continued Using" 
- Table columns: (1) user id (2) total number of times skill performed (3) optionally, if easy to implement ``last performed`` date
- Provide a button that will take you to user's details (similar what users table does today)

**Comment by dwalizer** [comment]
PR #1801

**Comment by rmmayo** [comment]
:+1:
