### ISSUE TITLE
Error when deleting 'VersionOutOfDate' errors from the Issues page

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1684]
Attempting to delete any `VersionOutOfDate` error results in the error page, and shows a a 403 error in the browser.  The initial `DELETE` request actually returns a 400 error, which then causes the subsequent call to retrieve the project to use undefined, that shows as a 403 (b/c projectId undefined does not exist)

Example `DELETE` request URL: 

`https://<SKILLTREE-HOST>/admin/projects/movies/errors/VersionOutOfDate/The%20version%20used%20(%40skilltree%2Fskills-client-vue-3.0.0)%20is%20out%20of%20date%20(latest%20is%203.4.1).%20%20Please%20consider%20upgrading%20the%20client%20version.`

![image](https://user-images.githubusercontent.com/47030042/192790456-e2bca39a-f842-419d-9c4e-c9df0887fa96.png)

![image](https://user-images.githubusercontent.com/47030042/192790787-87ff0a83-5709-415c-ac55-bdec94197486.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1685

**Comment by sudo-may** [comment]
:+1:
