### ISSUE TITLE
Change wording of message in self report "reject skills" modal

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1697]
Change "This will **permanently** reject user's request(s) to get points...."  to "This will reject the user's request(s) to get points..."

![image](https://user-images.githubusercontent.com/47030042/194111420-09ff0e67-8d4f-4d89-833b-c32f8e242c0f.png)

**Comment by mosefer** [comment]
PR: #1701

**Comment by rmmayo** [comment]
:+1:
