### ISSUE TITLE
Changing a Skill from Approval Required to Honor System incorrectly reports pending requests

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1699]
If a self report approval required skill is edited and changed to honor system, the edit skill dialog incorrectly reports previously approved requests as pending requests that will be automatically approved.

To replicate
1. create a self report approval required skill
2. request points for that skill
3. approve the requested points (ensure that there are no other pending requests for that skill)
4. edit the skill and change from approval required to honor system

![image](https://user-images.githubusercontent.com/61209506/194347854-dd812445-1ff2-4ed5-ad39-0b797112bd92.png)

**Comment by dwalizer** [comment]
:+1:
