### ISSUE TITLE
user_points rows are not removed when a skill is deleted

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#1700]
If a skill is deleted, any related rows in user_points are not removed. This is of particular note when a user only has points for the deleted skill in that project, which results in an entry in the Project Users view for a user with 0/X,XXX points and a Points Last Earned date of NaN/Invalid Date

**Comment by mosefer** [comment]
PR: #1705

**Comment by rmmayo** [comment]
All user_points rows are removed when the skill is deleted directly, but there is still a user_points record for the project left behind when the skill is removed by deleting the subject it belongs to.  This results in the same invalid entry in the Project Users view.

![image](https://user-images.githubusercontent.com/47030042/196247832-dfeabc80-5904-4898-bfe5-686c3b02e44e.png)

**Comment by rmmayo** [comment]
created #1713 to address the issue when the skill is removed via the parent subject
