### ISSUE TITLE
Ability to split self-approval workload between multiple Approvers or Admins

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1702]
Create a flexible way for project admins to configure a split of the self-approval workload:
* users can be assigned one-by-one to a specific approver/admin
* users can be assigned by user's tag (server config optionally enabled feature)
* ability to designate a catch-all approver - designate an approver for any users that are not already assigned to an approved
   * as a fallback, if such person is not designated then approve requests will be forwarded to the admins

Depends on #648

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1812

**Comment by dwalizer** [comment]
:+1:
