### ISSUE TITLE
Improve Issues warning language on the project card

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1711]
Improve Issues warning language on the project card:
![image](https://user-images.githubusercontent.com/51749745/195588857-e21c0a72-3f71-41bd-ac3b-50313f0a5b0b.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1734

**Comment by dwalizer** [comment]
:+1:
