### ISSUE TITLE
Navigating from a Global Badge to a Cross Project Skill is broken

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#1717]
If a Global Badge has skills from more than one project, when the user goes to the Global Badge's page and clicks on the name of one of the cross project skills to view the skill page, there's instead an error like so:

`Invalid token - proxyingSystemId [proj1] does not match resource projectId [proj2]`

**Comment by mosefer** [comment]
PR: #1743

**Comment by dwalizer** [comment]
:+1:
