### ISSUE TITLE
Sorting broken on Subjects/Badges/Skills/Points columns on Pin Project dialog

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#172]
Sorting on Subjects, Badges, Skills, or Points columns only works the first time the dialog is rendered (and only once for any of those four columns), page must be reloaded to regain one time sorting. Sort icons are not rendered for Subjects/Badges/Skills/Points.

**Comment by rmmayo** [comment]
this is the default behavior for BootstrapVue  v-table, clicking 

> Clicking on a non-sortable column will clear the sorting (the prop no-sort-reset can be used to disable this feature).

@sudo-may  - maybe we should disable the default "clear the sorting" behavior?  what do you think?

**Comment by sudo-may** [comment]
@rmmayo - I concur, let's disable it

**Comment by rmmayo** [comment]
PR: #177
