### ISSUE TITLE
Dashboard falsely reports badge as disabled if all skills are removed

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#173]
To reproduce, 
1. create a badge (global or project). 
1. add a skill to the badge
1. publish the badge
1. Manage badge, remove skill (there should be zero skills on the badge now)
1. Badge should report that it is Live not Disabled

(note that this bug is also present in Global Badges that have zero skills but have project levels)

**Comment by sudo-may** [comment]
Manual tests passed
