### ISSUE TITLE
``register_root_user_spec.js `` fails sporadically in CI run

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1737]
![image](https://user-images.githubusercontent.com/51749745/197180575-3f3845a8-cc15-443a-bad7-dcd8322c1e46.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1740

**Comment by rmmayo** [comment]
:+1:
