### ISSUE TITLE
Skills Display: selected skill filter overlaps Last Viewed button

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1744]
![image](https://user-images.githubusercontent.com/51749745/198065345-0f9a8b5f-46f1-46ab-aee9-4af66ad7f4db.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1750

**Comment by dwalizer** [comment]
:+1:
