### ISSUE TITLE
Global badge skills table mistakenly show ``Manage`` button for the skill that was added

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1748]
- navigate to ``/administrator/globalBadges/<global_badge_id/``
- add a skill

![image](https://user-images.githubusercontent.com/51749745/198284726-bbf93ee5-d03b-4a18-acb4-c93a2fc0f044.png)

- ``Manage`` button is mistakenly displayed
- Refresh and the button is gone

**Comment by dwalizer** [comment]
PR #1766

**Comment by sudo-may** [comment]
:+1:
