### ISSUE TITLE
do not encode descriptions

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1758]
encoding descriptions is unnecessary and can cause issues with validation:

'skills.controller.exceptions.SkillException: Custom validation failed: msg=[Validation failed], type=[subject], subjectId=[subject2Subject], name=[subject 2], description=[\&gt; (U) quote]'

**Comment by rmmayo** [comment]
PR: #1762

**Comment by sudo-may** [comment]
:+1:
