### ISSUE TITLE
Validation doesn't indicate the reason for a failure on load

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#1768]
Loading a skill that has a validation problem in the description (ex. invalid text), unless you interact with the description box, the skill will not be able to be saved but it will not display an error message indicating that the description failed to validate - so if you change something unrelated to the description, such as the point increment, you will not be able to save the skill but won't know why.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1781

**Comment by dwalizer** [comment]
:+1:
