### ISSUE TITLE
 "Skip To Content" button when using keyboard based navigation 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1770]
- display a hidden button that is displayed on focus when using keyboard navigation 
- clicking on the button should put focus on the main content

Resource: 
https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/mouse-and-keyboard-events/skip-to-main-content/

As an example - GitHub has it implemented

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1819

**Comment by rmmayo** [comment]
:+1:
