### ISSUE TITLE
Breadcrumb bar inaccurate when viewing details of Subject User

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#179]
Following the application flow of:
1. Manage Project
1. Manage Subject
1. Subject Users
1. Click Details for Subject User

the breadcrumb bar goes from ```Home / PROJECT : Xyz / SUBJECT: abc / Users``` to
```Home / PROJECT: Xyz / Users / USER: def``` preventing navigation back to the subject via the breadcrumb bar.

**Comment by mosefer** [comment]
issue also present when viewing details for skill and badge users

**Comment by sudo-may** [comment]
manual test passed
