### ISSUE TITLE
In Private-Only mode when adding an approver the warning is not correct

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1791]
Private-only mode project display an additional warning when adding admins, that warning is mistakenly also displayed when adding approvers: 

![image](https://user-images.githubusercontent.com/51749745/200391531-fbee77c0-c4ec-4465-b5b5-0d7f2d14b273.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1792

**Comment by rmmayo** [comment]
:+1:
