### ISSUE TITLE
Add "Contact Project" button to the project table on the "Manage My Projects" page

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1802]
Currently, users would have to click into the individual project's skill-display from the Progress and Rankings page to access the "Contact Project" button.  Adding the button to the project table of the Manage My Projects page would allow  a user to contact any project directly without having to add the project to their Progress and Rankings view and then visit the individual project skill-display page.

**Comment by sudo-may** [comment]
similar to #2045

**Comment by sudo-may** [comment]
:+1:
