### ISSUE TITLE
Ability to export project's training profile to perform further analysis 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1809]
Investigate what it would take to export project's training profile to csv or excel format for further analysis

**Comment by rmmayo** [comment]
PR: #2862

**Comment by sudo-may** [comment]
Feedback based on testing: 
- Improve export of the `Expiration Column` to:
 -  `Daily: every 90 days`, `Yearly: on September 16th` and `Monthly: on 1st`
 - Remove group rows from the export and change the export button to `Export All Skills`
 - Add `Up to N occurences` information to the `Time Window` column

**Comment by rmmayo** [comment]
PR #2: #2871

**Comment by sudo-may** [comment]
:+1:
