### ISSUE TITLE
Add ability to display user-tag-based metrics on subject and skill pages

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1814]
On the skill metrics pages add ability to *optionally* show: 
- bar chart or pie chart for users that **achieved** the skill - breakdown of user tag values based on the configured tag key
- bar chart or pie chart for users that are in **progress** for that skill - breakdown of user tag values based on the configured tag key 

On the subject  metrics pages add ability to *optionally* show: 
- bar chart or pie chart for each **level** - a breakdown of user tag values based on the configured tag key

**Comment by dwalizer** [comment]
PR #1985

**Comment by sudo-may** [comment]
Follow on improvement: https://github.com/NationalSecurityAgency/skills-service/issues/2015

**Comment by sudo-may** [comment]
looks like the filter uses an `OR` operator when locating  tags which is different from the "Skill Usage Filters"; change the filter to use `AND` operator instead

**Comment by sudo-may** [comment]
:+1:
