### ISSUE TITLE
Display user tags on the user page 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1815]
If a user has user tags then display them on the Dashboard's user page (``/administrator/projects/<projId>/users/<userId>``)
- if user tag has a metrics page then link to the metric page

**Comment by dwalizer** [comment]
PR: #1955

**Comment by rmmayo** [comment]
The user tag is add to the user page, but it does not link to the user tag metrics page (`/administrator/projects/<projId>/metrics/userTag/<userTagKey>/<userTagValue>`)

**Comment by rmmayo** [comment]
PR: #1965

**Comment by dwalizer** [comment]
PR #1968

**Comment by rmmayo** [comment]
:+1:
