### ISSUE TITLE
Add number of missing inception skills and improve descriptions

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1831]

**Comment by sudo-may** [comment]
New Skills Created: 

**Subject: Projects**
copy a project
share project
changer order of subjects
change order of badges

**Subject: Skills** 
Search and Navigate directly to a skill
Create Aesthetically Pleasing Description
Copy Skill
create skill group
reuse in project
move skills
import skills form catalog
change order of skills
Add addition columns to the skills table

**Subject: Dashboard**
Learn about Project Access Options
send success story
teach someone else
export to catalog
suggest tool integration 
suggest a feature

-----

New Badges: 
- Community Super Hero
- Admin Starter
- Metrics Ninja
- Catalog User
- Skills Organizer
- Promoter

**Comment by sudo-may** [comment]
https://github.com/NationalSecurityAgency/skills-service/pull/1881

**Comment by rmmayo** [comment]
:+1:
