### ISSUE TITLE
Do not change case for user tag value in Configure Approval Workload

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1834]

**Comment by rmmayo** [comment]
note: the User Tag Label is also being lower cased and should not be "Users in `xxx`" where `xxx` is the label but all lower case

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1841

**Comment by rmmayo** [comment]
:+1:
