### ISSUE TITLE
Missing buttons for approver role

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1847]
New Project button is missing when:
- navigate into a project where user is an Approver
- click on "Projects" on the breadcrumb
- "Project +" button on top right is not shown

Metrics navigation buttons are missing
- navigate into a project where user is an Approver
- click on metrics tab 
- Metrics navigation buttons on top right are not shown

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1848

**Comment by rmmayo** [comment]
@sudo-may it looks like the metrics navigation buttons are still not displaying after following the steps outlined above

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1853

**Comment by rmmayo** [comment]
:+1:
