### ISSUE TITLE
Content of code block is not preserved in the Rich Text Editor

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1851]
- create new skill
- create a code block with code inside of it, for example ``<skills-display version="0"/>``
- save
- edit the skill again - the code of ``<skills-display version="0"/>`` is gone

Please note that this also happens to the in-line code as well

**Comment by sudo-may** [comment]
@rmmayo ``<skills-display version="0"/> `` is still removed from the code block

**Comment by rmmayo** [comment]
@sudo-may I'm guessing this change had not been deployed yet when you tested.  I just tried again and it worked for me:

![image](https://user-images.githubusercontent.com/47030042/206449589-0f1cb1c2-0607-4f02-82e8-55a98ebc5ae1.png)

**Comment by sudo-may** [comment]
:+1:
