### ISSUE TITLE
Disable signup link on the login page

### ISSUE THREAD

**Issue by Nomango** [NationalSecurityAgency/skills-service#1856]
Thank you for providing such a great platform, well done!
One question I have is, is it possible to disable the signup button on the login page? Because I don't want my site to be logged in by strangers, so it would be good to leave only one root user.

**Comment by Nomango** [comment]
Or it may be a better design to configure the list of emails that are allowed to register in the dashboard settings.

**Comment by sudo-may** [comment]
@Nomango Thank you for the kind words! Unfortunately, currently there is no mechanism to configure an access list for the dashboard. There is an exciting ticket [#1017 Invite-only dashboard Admin access ](https://github.com/NationalSecurityAgency/skills-service/issues/1017) that I believe would satisfy your needs. I would encourage you to subscribe to #1017 ticket (and maybe even comment on it) so you'll be notified when the progress is made. I am going to close this ticket in favor of #1017. 

Thank you for being part of the SkillTree Community!
