### ISSUE TITLE
Skills display: show "no results message" when tag filter + attribute filters are selected and there are 0 results

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1867]

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1878

**Comment by rmmayo** [comment]
@sudo-may this is not working on integration.  Pretty sure the problem is that `selectedTagFilters` was changed from a Set to an array in #1859

**Comment by rmmayo** [comment]
PR: #1890

**Comment by rmmayo** [comment]
:+1:
