### ISSUE TITLE
Add display and filtering of Skill Tags to the Project's Skill Metrics

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1871]
``/administrator/projects/{projectId}/metrics/skills``

**Comment by dwalizer** [comment]
PR #1996

**Comment by rmmayo** [comment]
PR: #1996

**Comment by sudo-may** [comment]
looks like the filter uses an OR operator when locating tags which is different from the "Skill Usage Filters"; change the filter to use AND operator instead

**Comment by dwalizer** [comment]
Addressed in PR #2042

**Comment by sudo-may** [comment]
:+1:
