### ISSUE TITLE
Number of minor issues with new metrics

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#189]
- ``skills``: links do not work: 
![image](https://user-images.githubusercontent.com/51749745/100912508-8e313a00-349e-11eb-96a4-084b392ee667.png)

- ``Number of users for each level for each subject``: see if there a way to visually separate subjects 
![image](https://user-images.githubusercontent.com/51749745/100912889-0d267280-349f-11eb-9a31-02a09150c6f9.png)

- ``Number of users for each level over time``: time series need to extend to the latest date
![image](https://user-images.githubusercontent.com/51749745/100913065-46f77900-349f-11eb-8fab-4fa126669c3e.png)

**Comment by mosefer** [comment]
* the order of items plotted on the graph doesn't match the order that they're displayed in the legend (evident in both screenshots above)
* the topic icon is identical to the view user/user metrics buttons in look and feel, which makes it appear to be a non-functioning action button
![image](https://user-images.githubusercontent.com/61209506/100924690-ef610980-34ae-11eb-8517-849adfc57703.png)

**Comment by mosefer** [comment]
* Sorting on the Type, Name, and Level columns in the Achievements metrics table triggers an error page, it looks as if the ```/admin/projects/movies/metrics/userAchievementsChartBuilder``` end point returns a 400 in those cases.

**Comment by mosefer** [comment]
Skill Metrics view, Last Achieved info card displays the date as ```This skill was last achieved on 2020-11-28 13:21```, however, in the client display we display dates as ```November 23rd 2020``` for achieved on. Should we use the same format in the dashboard (but add time)?

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/192

**Comment by rmmayo** [comment]
the Skill Metrics view, Last Achieved info card still displays the date as This skill was last achieved on 2020-11-28 13:21, assuming that was left unchanged on purpose?

**Comment by mosefer** [comment]
> the Skill Metrics view, Last Achieved info card still displays the date as This skill was last achieved on 2020-11-28 13:21, assuming that was left unchanged on purpose?

@sudo-may  and I discussed this, left as-is intentionally.
