### ISSUE TITLE
Self Report Workload: Configuring all skills under a subject fails when that subject has a group

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1894]
Add All skills  under a subject:
![image](https://user-images.githubusercontent.com/51749745/206702044-993f261c-6c27-44ae-a7b7-0677d3e8c3c2.png)

An error example: 
![image](https://user-images.githubusercontent.com/51749745/206701856-bd9ad4c8-3fb7-4441-b216-8178d74c14de.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1897

**Comment by rmmayo** [comment]
:+1:
