### ISSUE TITLE
Migrate away from vue-multiselect

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#190]
vue-multiselect has many open issues and appears to have stagnated in it's addition of a11y support. Consider another multi-select plugin with better a11y support and more active development. 

https://www.primefaces.org/primevue/showcase/#/multiselect for example

**Comment by mosefer** [comment]
https://github.com/sagalbot/vue-select

**Comment by rmmayo** [comment]
PR: #1419

**Comment by rmmayo** [comment]
commit comments referenced the wrong ticket (#191) by accident

**Comment by mosefer** [comment]
:+1:
