### ISSUE TITLE
Inception's ``Root Help Url`` setting is not respected; some of the external links are wrong

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1906]
![image](https://user-images.githubusercontent.com/51749745/207104040-cb6926bd-cb5f-422b-bd68-ab7b58d0319a.png)

Skills with wrong Help URL: 
- Add Project Administrator

Add Help URL: 
- Visit Badges
- Visit Project Dependencies

Enhance Project Description
- Preview Client Display for Project

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1907

**Comment by rmmayo** [comment]
:+1:
