### ISSUE TITLE
``Delete All`` on the Performed Skills page does not show loading during its operation

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1910]
Clicking on ``Delete All``  on the ``Performed Skills`` page may take several seconds and "Loading..." is not shown. 

Looks like the issue is in ``UserSkillsPerformed.vue`` and that it is setting ``isLoading`` which is not actually used to display loading status (and should be removed); looks like ``table.options.busy`` needs to be utilized instead

**Comment by dwalizer** [comment]
PR #1911

**Comment by dwalizer** [comment]
Updated PR #1913

**Comment by sudo-may** [comment]
:+1:
