### ISSUE TITLE
Add competitive aspect to badges

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1924]
**General Idea:**
Introduce a sense of urgency to badges 
- ex. if a badge is completed within X days they get a special gold-version of the badge or an additional tag etc...

**Visualize sense of time urgency on Skills Display:**  
- the clock starts for a user when the first skill event is reported to one of the skills under the badge
- display remaining time 
- if achieved within the configured time then display the special version of that badge, some of the ideas:
   - "Race Car Award" with a car icon overlaid on the badge
   - "On time award" with an award or clock icon
   - golden star or multiple stars
   - clearly communicate that this award is due to timely achievement (within the time challenge)
 - optional: for the user that achieved the badge first - display "First to achieve" award tag overlayed on the badge; 
 - make sure new visualization is accessible
 - verify it works in a themed Skills Display

**Admin: When creating a badge**
- ability enable "Time Urgency" feature which will allow to configure number of days

Side note: Other follow-on ideas (not in this ticket): badge specific leader-boards and/or adding badges to existing leaderboard (#2309)

**Comment by rmmayo** [comment]
:+1:
