### ISSUE TITLE
Prev / Next buttons are missing if there's a gap in the display order

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1925]
![image](https://user-images.githubusercontent.com/47030042/208965964-6f2812e5-f72a-4f57-9f2b-47ba62f72783.png)

![image](https://user-images.githubusercontent.com/47030042/208966099-c247bec6-d39b-4aec-8c36-557571e06d84.png)

**Comment by dwalizer** [comment]
PR #1943

**Comment by rmmayo** [comment]
:+1:
