### ISSUE TITLE
Changing the point value of an imported skill leads to unexpected point totals in the users table and client display

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1936]
Created a skill with a single occurrence and total point value of 100 points in project A.  Reported the skill for the current user (achieving the skill and earning 100 points).  Then imported the skill into project B, but changed the point total in the local project to 5 points.  After finalizing, the users table for that skill showed "2000% - 100 / 5 points"
![image](https://user-images.githubusercontent.com/47030042/210630040-9034b750-b84a-4dcd-83db-100a7236e7f8.png)

and the client display also listed 100 / 5 points.

![image](https://user-images.githubusercontent.com/47030042/210630259-12993258-f069-4c57-912f-1c2ef23b96c0.png)

**Comment by dwalizer** [comment]
PR #2055

**Comment by sudo-may** [comment]
:+1:
