### ISSUE TITLE
Display badge's lifecycle status inside of an information card and remove "Go Live" button once bade is live

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1940]
Utilize info card for badge's Live/Disable status (similar to the way project's visibility is handled): 

![image](https://user-images.githubusercontent.com/51749745/210804719-59740231-e350-449e-b1a3-62d0b5bf9143.png)

Once bade is enabled remove "Go Live" button

**Comment by dwalizer** [comment]
PR: #1946

**Comment by sudo-may** [comment]
:+1:
