### ISSUE TITLE
Rich Text Editor Improvements

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1941]
- change wording to "Insert images and attach files by..."
- recognize when the link is a download from skills server and in that case use `<i class="fas fa-download"></i>`
- prevent non-pdf files from opening in a new tab
- Change error message for unknown file type: 
> Unable to upload attachment - File type is not supported. Supported file types are .xlsx, .docx, .pptx, .doc, .odp, .ods, .odt, .pdf, .ppt, .xls
- format bytes for error message to be human readable (eg, 1377 -> 1.34 kB) when attachment exceed max size
- disable attachments for emails

**Comment by rmmayo** [comment]
PR: #1950

**Comment by rmmayo** [comment]
PRL #1958

**Comment by rmmayo** [comment]
PR: #1960

**Comment by dwalizer** [comment]
:+1:
