### ISSUE TITLE
Add ability to configure custom warning message when files are uploaded to a description 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1942]
- add ability to configure server-side custom message
- when message is configured and a file is added to a description display the configured warning 
- one idea is to display the warning right below the "Insert images..." messages in the footer: 
![image](https://user-images.githubusercontent.com/51749745/210807821-df0637d6-3def-4df9-aa56-26ab4d853a74.png)

**Comment by rmmayo** [comment]
PR: #1951

**Comment by rmmayo** [comment]
PR: #1959

**Comment by sudo-may** [comment]
:+1:
