### ISSUE TITLE
Ability for subject's skills to depend on a level completion in a different subject

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1976]
- Ability to configure at subject level 
- Client display with show a lock icon with a clear explanation of the dependency and what it will take to get there
  - link to the dependent subject and maybe show the current progress

**Comment by dwalizer** [comment]
Admin View
1. Rename "Dependencies" to "Learning Path"
2. Rename other instances to "Prerequisite" in the display/controls of nodes
3. Add controls to the project dependency page to allow the addition of prerequisites to a skill
4. Add the ability to click on nodes to add or remove a prereq

Skills Display
1. Enhance dependencies graph to support Subject's level - Subject Completion Dependency could say Subject Name and required level beneath it; clicking would take you to the subject page
2. Modify message on Skill page / expanded description to indicate something like ** Reach level 2 in Some Subject to enable this skill. ** where applicable
3. Also modify message on Skill page / expanded description to indicate something like ** Complete 1 prerequisite skill to enable this skill **

**Comment by sudo-may** [comment]
Learning Path implementation allows to configure badges as prerequisites for other badges/skills allowing users to simulate subject-based prerequisites by adding subject's skills to a badge and then using it in a learning path.
