### ISSUE TITLE
Subject's metrics erroneously counts users from other projects when subjectId happen to be named the same

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1978]
The issue is in the ``NumUsersPerSubjectPerLevelMetricsBuilder`` class, specifically ``skills.storage.repos.UserAchievedLevelRepo#countNumUsersPerContainerTypeAndLevel`` needs to consider project for both sides of the join

**Comment by dwalizer** [comment]
PR #1980
