### ISSUE TITLE
On Skills Display add ability to search all skills names across all the subjects

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1982]
Add a search box above subject cards that will allow to locate skills by name across all the subjects
- One idea is to wrap subjects cards within a card/border to logically group them together; then search box could be placed in the outer card (on the top)
- search box should suggest skills as text is entered in the search box
- suggest should feature (1) name of the skill (2) subject name (3) skill attributes (ex. self report)
- clicking on a skill will take you to the skill page

**Comment by dwalizer** [comment]
:+1:
