### ISSUE TITLE
Display wrong badge quantity at dashboard

### ISSUE THREAD

**Issue by kstan79** [NationalSecurityAgency/skills-service#1990]
I notice the badge at dashboard display 3 (in actual is 1), when click into the badge link it give me 1. Maybe there is some error in condition check

![Screenshot 2023-02-14 at 5 12 44 PM](https://user-images.githubusercontent.com/1889979/218750637-eed82f54-7f5a-4dcd-bec0-cf1416e77c5b.png)
![Screenshot 2023-02-14 at 5 12 39 PM](https://user-images.githubusercontent.com/1889979/218750648-2bf394d3-aabf-4d84-9bee-fce3ae1519d8.png)

**Comment by dwalizer** [comment]
Hello!  At the moment, I can't seem to replicate this issue.  Could you give us a bit more information on your setup?  I.e. the version of SkillTree you're using, if you have more than one project, etc.  That should help to narrow down what could be causing this issue.  Thank you!

**Comment by kstan79** [comment]
Cause my data changed, I cant track issue now. But I can recall that the badge either from another project, or from global badge.
Beside, I'm using v2.3.3, fresh install

**Comment by dwalizer** [comment]
Do you recall if you made any changes to the badges which could've caused them to become achieved?  For example, removing a skill from a badge.  Or were all the badges achieved normally, through achieved skill events?

Also, are you using H2 for your instance?

**Comment by kstan79** [comment]
1. no im didnt change anything, outside show 3, inside show 1
2. im use postgresql

**Comment by dwalizer** [comment]
Can not reproduce, closing
