### ISSUE TITLE
Add Publish Function In Subject

### ISSUE THREAD

**Issue by kstan79** [NationalSecurityAgency/skills-service#1991]
I'm trying to implement skilltree subject by subject without js frontend.

while Im preparing 2nd subject and skill, there is people start claim the new skill which I'm not yet want to publish (from dashboard ui). I would like to suggest "publish" function similar like badge, when not ready it is hidden

**Comment by sudo-may** [comment]
@kstan79, Thank you for the suggestion! We have documented the request via https://github.com/NationalSecurityAgency/skills-service/issues/1993 ticket so please feel free to follow that ticket. Have a great day!
