### ISSUE TITLE
Delete badge

### ISSUE THREAD

**Issue by kstan79** [NationalSecurityAgency/skills-service#1992]
sometimes there is some human error cause badge assign to specific users (like assign wrong required skills ). Event though the problem fix but there is no way to revoke the given badge, is there anyway to remove the badge?

**Comment by sudo-may** [comment]
@kstan79 thank you for reaching out. Badge achievement corresponds to badge's requirement so once all of the required skills are achieved then the badge is awarded. If a skill achievement was reported by mistake then it can be easily removed by deleting one or more of Skill Events (Navigating to ``Project -> Users -> Select a User -> Performed Skills``)

https://skilltreeplatform.dev/dashboard/user-guide/users.html#performed-skills

After the deletion of a Skill Event for one of the badge's required skills the badge achievement will be removed by the system automatically. I hope this helps!

**Comment by kstan79** [comment]
nice it fixed! However it maybe good for you guys add FAQ in documentation page, explain how it work! Thanks!
