### ISSUE TITLE
Admins must still invite themselves to private projects

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#1994]
If a project is made Private, Admins will get Access Denied errors from the non-admin UI on the project unless they are also invited to the project

Steps:
1. Preview the project - good
2. Set project to private
3. Try to preview again - good
4. Send invite
5. Try to preview again - FAIL

**Comment by dwalizer** [comment]
PR #2014

**Comment by rmmayo** [comment]
:+1:
