### ISSUE TITLE
Keep track of individual skill occurrences after skill completion

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#200]
When reporting a skill, the skill event is not recorded when:

1. the skill has reached it's maximum points
1. the skill is not within the allowable time window (occurred to soon after the last time the skill was reported)
1. the skill's dependencies have not been met

In order to track usage over time to gauge usefulness/popularity of a skill, it has been requested that we keep track of the skill usage over time, even if the skill occurrence did not apply due to one of the above reasons.

Will need to discuss feasibility as well as impact to performance and increased data storage.

**Comment by sudo-may** [comment]
The plan is to evaluate Redis for persisting all of the skill events regarding of their contribution to user's score; as a part of this exercise let's evaluate: 
- scalability - we could consider only keeping last N years of data (configurable?) 
- feature set - ability to analayze the events in real time and/or via async batch

**Comment by mosefer** [comment]
Work was completed in another ticket - #275
