### ISSUE TITLE
Support quarkus for cloud native

### ISSUE THREAD

**Issue by kstan79** [NationalSecurityAgency/skills-service#2004]
Quarkus offer much flexible and easier implementation on cloud native environment, would you guys plan to support quarkus?

**Comment by sudo-may** [comment]
@kstan79 thank you very much for reaching out! Unfortunately there are no plans to support Quarkus. SkillTree is designed to be environment agnostic with an ability to run in any docker, cloud or even single server environment. In addition, SkillTree takes advantage of Spring Boot framework so a transition to Quarkus would be quite onerous. Hopefully that makes sense and thank you again for asking!
