### ISSUE TITLE
Metrics have couple inconsistencies

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#201]
- achievements table is using user_id instead of username
- achievements table links to user metrics that do not exist  -remove link
- change message for skill's metrics 'Achievements over time' when there are no achievements to be 'This chart needs at least 1 day of achievement(s)."

**Comment by mosefer** [comment]
@sudo-may  - Skill -> Achievement's over time chart still displays "No achievements yet for this skill." as opposed to the updated language specified in this ticket.

**Comment by sudo-may** [comment]
@mosefer - decided to change the verbiage - I think it sounds better than what the ticket suggested. What do you think?

**Comment by mosefer** [comment]
I'm fine with that. All other issues tested :+1: so closing this ticket now.
