### ISSUE TITLE
When assigning a quiz/survey to a skill calculate achievements for its catalog-imported skill replicas

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2022]
1. create a skill and export it to the catalog
2. import skill in the another project
3. create quiz or survey and achieve it
4. associate quiz with the skill crate in step one
5. validate that the achievement propagated to the imported skill

**Comment by sudo-may** [comment]
pr: https://github.com/NationalSecurityAgency/skills-service/pull/2040

**Comment by dwalizer** [comment]
:+1:
