### ISSUE TITLE
Change `Self Report` card to use Quiz/Survey terminology rather than existing "Test" verbiage

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2024]
![image](https://user-images.githubusercontent.com/51749745/225046714-96d25735-dfbe-46d8-aa46-18613db51611.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2041

**Comment by rmmayo** [comment]
:+1:
