### ISSUE TITLE
Changing an exported skill before finalizing it in another project breaks the skill's connection

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#2047]
How to recreate:
- Create two projects, Proj 1 and Proj 2
- Create a skill in Proj 1, then export it to the Catalog
- In Proj 2, import the skill, but *do not* finalize
- Return to Proj 1 and go to the Skill
- Edit the Skill's point value and save
- Return to Project 2

Finalization message will now be gone, the imported skill will still be present but won't retain the linked info from the original project (such as user completion), but will still say that it's an imported skill

**Comment by dwalizer** [comment]
PR #2060

**Comment by rmmayo** [comment]
:+1:
