### ISSUE TITLE
Users in ``Private Invite Only`` project with an Approver role are denied access

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2051]
when visiting `/administrator/projects/project-id/`
looks like ``/api/projects/privateproject2/customIconCss`` is returning `403` which causes 
![image](https://user-images.githubusercontent.com/51749745/226367844-7daff8c8-9cf5-447b-a92c-83b629f23b8d.png)

**Comment by rmmayo** [comment]
PR: #2054

**Comment by sudo-may** [comment]
:+1:
