### ISSUE TITLE
Admin users are not able to view quiz status or run a quiz on behalf of another user

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2056]
- navigate to user's Skills Display preview (``/administrator/projects/<project-id>/subjects/<subject-id>/skills/<skill-id>/users/<user-id>/``
- drill down to a skill that has a quiz or a survey assigned to it
- attempt to take the survey/quiz

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2139

**Comment by dwalizer** [comment]
:+1:
