### ISSUE TITLE
Remove `Time Limit` form quizzes' splash screen

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2070]
![image](https://user-images.githubusercontent.com/51749745/227182967-3a82f844-b84b-4f1c-af74-3c8f4c7357dd.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2074

**Comment by dwalizer** [comment]
:+1:
