### ISSUE TITLE
If a not supported document type is attempted to be uploaded to a description then the error is never cleared and the only choice is to cancel that modal

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2076]
![image](https://user-images.githubusercontent.com/51749745/227314369-6c82ba34-9081-4265-a1a5-7a0a33aef33a.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2077

**Comment by dwalizer** [comment]
:+1:
