### ISSUE TITLE
Define User Avatar

### ISSUE THREAD

**Issue by kstan79** [NationalSecurityAgency/skills-service#2083]
Is there anyway to upload avatar, or get from gravatar? Currently the UI look dry.

**Comment by sudo-may** [comment]
@kstan79 Thank you for asking! Unfortunately that feature doesn't exist but we thought it was a good idea and created a ticket #2090 which documents several ideas on how an Avatar could be utilized in the SkillTree Dashboard. Thank you for being part of the SkillTree community!
