### ISSUE TITLE
On the `Manage My Projects` page viewing project description only works for project admin of that project 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2084]
- create new project and configure a description
- change project's settings 
  - `Project Visibility: Discoverable on Projects and Rankings`
  - `Project Description: Show Project Description Everywhere`
- log in as a non-admin users of that project and navigate to the `Manage My Projects` page
- attempt to view the description

**Comment by rmmayo** [comment]
:+1:
