### ISSUE TITLE
Ability for skills to depend on a completion of a badge

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2092]

**Comment by dwalizer** [comment]
Admin View

1. Rename "Dependencies" to "Learning Path"
2. Rename other instances to "Prerequisite" in the display/controls of nodes
3. Add controls to the project dependency page to allow the addition of prerequisites to a skill
4. Add the ability to click on nodes to add or remove a prereq

Skills Display

1. Enhance dependencies graph to support Subject's level - Subject Completion Dependency could say Subject Name and required level beneath it; clicking would take you to the subject page
2. Modify message on Skill page / expanded description to indicate something like ** Reach level 2 in Some Subject to enable this skill. ** where applicable
3. Also modify message on Skill page / expanded description to indicate something like ** Complete 1 prerequisite skill to enable this skill **

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2222

**Comment by sudo-may** [comment]
:+1:
