### ISSUE TITLE
User Communities authorization at the project level

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2093]
Utilize existing user tags to configure key(s) that will represent user communities that will provide another way to authorize users access at the project-level, both for administrative project views as well as progress&ranking views

**Comment by rmmayo** [comment]
Note: may need to consider adding a special user community based `skills.config.ui.paragraphValidationRegex` as well as user community based custom header/footer.

**Comment by rmmayo** [comment]
PR: #2186

**Comment by sudo-may** [comment]
:+1:
