### ISSUE TITLE
In certain cases emails do not handle special characters 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2107]
- when using contact users or admins forms
- copy and paste from libre office or Microsoft products into email's body something like ``Ok let’s try something basic``
- send an email with that body
- that email is rendered then as ``Ok let?s try something basic`` and looking at the source of the body the value ``Ok let=E2=80=99s try something basic``

**Comment by dwalizer** [comment]
PR #2121

**Comment by sudo-may** [comment]
looks like if the pasted value has `\n\n` (new lines) they are still not respected; I think we should take a look at calling `.getHTML()` on the text editor and then passing that to the backend to utilize as an email body in order to accurately represent the email

**Comment by sudo-may** [comment]
:+1:
