### ISSUE TITLE
Docker image prints password to logs

### ISSUE THREAD

**Issue by Nomango** [NationalSecurityAgency/skills-service#2118]
When deploying using the `skilltree/skills-service` image, the `SPRING_PROPS` environment variable will be printed to the log, which includes the password for the database. This poses a security issue.

**Comment by sudo-may** [comment]
@Nomango thank you for reporting, the fix/ticket was assigned to the next patch

**Comment by sudo-may** [comment]
Let's render any password as ``******`` but provide an ability to supply an optional parameter to print passwords for debugging purposes

**Comment by dwalizer** [comment]
PR #2129

**Comment by sudo-may** [comment]
@Nomango the fix ended up making into 2.5.0 release which is now available. Thank you again for reporting!
