### ISSUE TITLE
Get a non-exsits skill through api causes a java.lang.NullPointerException

### ISSUE THREAD

**Issue by Nomango** [NationalSecurityAgency/skills-service#2131]
In order to integrate with my own system, I directly called some apis of skill service.

When I called `GET /admin/projects/movies/skills/Fake` it returned an error of 500. It would be nice if it returns 404 instead.

**Comment by rmmayo** [comment]
PR: #2141

**Comment by sudo-may** [comment]
@Nomango, thank you for reporting! The fix will be in 2.5.0 release.

**Comment by sudo-may** [comment]
:+1:

**Comment by sudo-may** [comment]
@Nomango 2.5.0 release is now available and contains this fix. Thank you again for reporting!
