### ISSUE TITLE
apex chart's menu is not visible for user tag charts on subject and skill pages

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2143]
apex chart's menu is not visible for user tag charts on subject and skill pages

the following menu is not visible:
![image](https://user-images.githubusercontent.com/51749745/232786164-c402f6bf-828c-46c5-abf9-25ce943358ff.png)

**Comment by dwalizer** [comment]
PR #2146

**Comment by sudo-may** [comment]
:+1:
