### ISSUE TITLE
Changing a project from percentage, to points, then back, causes incorrect warnings

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#2184]
When a project is changed from Percentage, to points, and back to percentage, this causes issues with the level calculation, generating errors that levels can't be reached in that subject.

After fixing this issue, be sure to address it in migration and clear the warnings.

**Comment by sudo-may** [comment]
pr https://github.com/NationalSecurityAgency/skills-service/pull/2185

**Comment by sudo-may** [comment]
:+1:
