### ISSUE TITLE
Add ability to add "Input Text" answer type to a quiz

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#2188]
Allow a Quiz admin to add a question for a quiz that allows the user to provide a "fill in the blank" type answer, similar to "Input Text" answer type that currently exists for Surveys.  This would likely require a person to review and approve/disapprove the answer as being correct.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2957

**Comment by rmmayo** [comment]
If a quiz with an input text question is taken, but the input text question is not presented to the user (the # of Questions per Quiz Attempt is less than the total # of questions), then quiz will still be put in the "requires grading" state even though the graded question was not answered.

**Comment by rmmayo** [comment]
:+1:

**Comment by rmmayo** [comment]
I configured a 6 question quiz to be 1 question per attempt, with randomize question order enabled.  There is 1 input question and 5 single choice questions.   Every attempt always seems to present the input text question and never shows any of the single choice questions.

**Comment by rmmayo** [comment]
update: unable to replicate the same question issue - I think it was showing the same input question  b/c I had already had a quiz in progress so it kept showing the same question which is the correct behavior.

:+1:
