### ISSUE TITLE
Achievement Navigator is not returning Global Badges

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#220]

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/222

**Comment by mosefer** [comment]
:+1:

**Comment by sudo-may** [comment]
Looks like we need to rollback this ticket as right now global badge achievements are shown in the projects that may not be long to a global badge; looking at the code it would be too expensive to figure it out

**Comment by sudo-may** [comment]
Rolled back
