### ISSUE TITLE
UC labels and cards are not rendered for the admin role `ROLE_SUPER_DUPER_USER`

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2205]
It appears that `/app/projects` endpoint takes a different path for `ROLE_SUPER_DUPER_USER` and doesn't return `userCommunity` attribute. Looks like `skills.services.admin.ProjAdminService#loadProjectsForRoot` needs to be updated to populate `userCommunity` value. The ticket can be tested via a service test(s).

**Comment by rmmayo** [comment]
:+1:
