### ISSUE TITLE
several `/api/` endpoints do not respect UC protection

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2208]
endpoints to fix: 
- `/api/myProgressSummary`
- `/api/metrics/allProjectsSkillEventsOverTimeMetricsBuilder`
- `/api/mybadges`

steps:
- create non-uc project
- non-uc user adds the project to "My Projects"
- UC protection is added to that project
- endpoints in the list above must not return the project/badge for that non-uc user

**Comment by rmmayo** [comment]
PR: #2219

**Comment by sudo-may** [comment]
:+1:
