### ISSUE TITLE
On the admin project page display UC label under the project name instead of an information card 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2213]
On the admin project page, (when enabled) UC label is shown in its own card. However when long values are configure for  ``skills.config.ui.userCommunityBeforeLabel`` and ``skills.config.ui.userCommunityAfterLabel`` the display is not optimal. Display UC label under project name instead.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2245

**Comment by rmmayo** [comment]
:+1:
