### ISSUE TITLE
Enhance accessibility of the learning path page

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2232]
- Improve `aria-label`s of buttons
- skip tabbed navigation of the graph and its controls so the data can be efficiently accessed and managed used from/to controls and the Path Routes table
- announce addition and removal of route paths

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2234

**Comment by rmmayo** [comment]
:+1:
