### ISSUE TITLE
Skills Display: duplicate entries in the table if more than 1 skill/badge has the same prerequisite 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2233]
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/c9a5f205-32aa-40e8-86b7-81e6b954c21a)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2236

**Comment by rmmayo** [comment]
:+1:
