### ISSUE TITLE
Description editor toolbar controls with dropdown do not allow keyboard-based navigation

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2258]
- `tab` to the `H - Headings` on the toolbar and press `Enter`
- Headings' drop-down is displayed but there is now way to navigate to it via keyboard

The same issue happens for the following controls on the toolbar:
- Insert Table

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2295

**Comment by sudo-may** [comment]
Added new shortcuts: 

| Feature        | Shortcut        | Explanation                                                                                                                                                         |
|----------------|-----------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Copy & Paste   | Ctrl+C / Ctrl+V | Paste anything from browser, screenshot, excel, powerpoint, etc.                                                                                                    |
| Headings       | Ctrl+Alt+t      | Supports 6 different sized heading                                                                                                                                  |
| Bold           | Ctrl+B          | Apply **bold** formatting to text                                                                                                                                   |
| Italics        | Ctrl+I          | Apply *italic* formating to text                                                                                                                                    |
| Strike         | Ctrl+S          | Apply ~~strike-through~~ formating to text                                                                                                                          |
| Font Size      | Ctrl+Alt+s      | Apply a specific font size to text                                                                                                                                  |
| Line           | Ctrl+L          | Insert a horizontal line seperator                                                                                                                                  |
| Blockquote     | Alt+Q           | Apply quote formatting to line(s) of text                                                                                                                           |
| Unordered List | Ctrl+U          | A bulleted list                                                                                                                                                     |
| Ordered List   | Ctrl+O          | A numbered list                                                                                                                                                     |  
| Indent         | Fn+Tab          | When creating a list, this indent the list one level                                                                                                                |
| Outdent        | Fn+Shift+Tab    | When creating a list, this outdent the list one level                                                                                                               |
| Image          | Ctrl+Alt+i      | Insert an image.  Images may be chosen from a local file, a URL, or copy and pasted.                                                                                |
| Link           | Ctrl+Alt+r      | A hyperlink to an external resource                                                                                                                                 |
| Attachments    | Ctrl+Alt+a      | Attach a file to the description.  Attached files will be stored on the SkillTree server and a link for downloading the attachment will be presented.               |
| Inline Code    | Ctrl+Shift+C    | Apply `code style` formatting inline                                                                                                                                |
| Code Block     | Ctrl+Shift+P    | Apply `code style` to a multiline section

**Comment by dwalizer** [comment]
:+1:
