### ISSUE TITLE
Delete button on skills page has extra keyboard-tab-based navigation 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2259]
- tab delete button of a skill
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/c0a5e81d-c62c-4a0d-9bda-5521ef607296)
- first time tab-based navigation places focus on the button but the button doesn't respond to the `Enter`, pressing `tab` one more time puts the button in the proper focus and `Enter` does initiate the modal

In this ticket figure out why there is an extra and unnecessary tab navigation of the delete button

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2279

**Comment by dwalizer** [comment]
:+1:
