### ISSUE TITLE
"Time Window" help message in the skill edit modal is not correct

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2260]
The current default state is unchecked: 
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/f23e504f-885a-49b7-9420-6a7c4710b0cd)

Current message: `Uncheck to disable. When disabled skill events are applied immediately.`

**Comment by dwalizer** [comment]
PR #2289

**Comment by rmmayo** [comment]
:+1:
