### ISSUE TITLE
Enhance aria-label for `top 10` and `10 around me` buttons

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2265]
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/44d43711-4443-45a5-a5c5-4bbd99c28f0d)

clearly state that clicking those buttons will update the leaderboard and note which one is currently selected

in addition enhance aria-labels for values in the cells

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2280

**Comment by dwalizer** [comment]
:+1:
