### ISSUE TITLE
Skills Display - `This Skill`'s name is null when learning path has badge1 -> badge2 path

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2300]
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/aae3cf86-8bcb-426d-921e-daefe9c5c90a)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2302

**Comment by rmmayo** [comment]
:+1:
