### ISSUE TITLE
Video Config Improvements 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2337]
∘ Preview - show total video duration in user friendly format
∘ Maximum length validation for captions and transcript input 
∘ Edit Skill Modal: (Please configure video settings first) is still rendered even though video is configured 
∘ Removing video settings should unset self-report=video
∘ Time frame should be disabled when self-report=video or self-report=quiz

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2342

**Comment by rmmayo** [comment]
:+1:
