### ISSUE TITLE
Skills Display: Add `Video` Filter to Self Reporting Filter

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2370]
Add `Video` Filter to Self Reporting Filter
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/9a41b7d0-28fb-42c4-8499-162b551717d6)

**Comment by dwalizer** [comment]
PR #2383

**Comment by rmmayo** [comment]
:+1:
