### ISSUE TITLE
Motivate users to continue exercising a skill by optionally expiring its achievement 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2374]
Add ability to configure number of days expiration **after** skill is achieved and allow users to retain the achievement. On Skills Display, once skill is achieved clearly show that user has to perform the skill in order to keep it within N days. Once user perform the skill the expiration will slide and the messages will adjust accordingly. 

If user failed to keep the achievement then:
-  remove user achievement, points, occurrences;
- recalculate project and subject points
- remove badge achievements if this skill is part of a badge
- expire associated quiz attempts 

Skills Display should be very transparent at reminding user that skills are going to expire and give plethora of notice.

**Comment by sudo-may** [comment]
enhance expiration configuration to allow users entering number of days to make multiple day changes easier (ex. going from 90 to 5)

**Comment by rmmayo** [comment]
PR: #2419

**Comment by sudo-may** [comment]
:+1:
