### ISSUE TITLE
Removing project setting also deletes in other projects

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2375]
- Create 2 projects and configure `Root Help URL` in both projects: 
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/d92d3296-1870-4c6c-87dd-43f2e843e100)
- Clear the `Root Help URL` in one of the projects and save
- Notice that the setting was also cleared in the other project

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2381

**Comment by dwalizer** [comment]
:+1:
