### ISSUE TITLE
Changing a self approval skill type should clear out requests

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#2379]
If a Self Approval with Justification skill receives a request from a user to be approved, and the type of the skill is then changed to a Video or a Quiz, the existing requests are not cleared out, which can prevent a user from taking the quiz or completing the skill.

![image](https://github.com/NationalSecurityAgency/skills-service/assets/12420708/c62ee746-0e39-44f9-8461-7b92fd07cbd3)

**Comment by dwalizer** [comment]
PR #2396

**Comment by sudo-may** [comment]
:+1:
