### ISSUE TITLE
Minor issues with project access management table 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2395]
**Issue 1:** suggest users that are already admins from other table pages - looks like table does not account for all users but rather only a current page
- make sure you created enough users to have more than 1 table page
- attempt to add user from another page

![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/857a80ce-6361-4989-a9f6-241665688cc6)

**Issue 2:** removing a user from `>1` page resets the table to the first page

**Comment by dwalizer** [comment]
PR #2447

**Comment by rmmayo** [comment]
:+1:
