### ISSUE TITLE
Modifying email settings doesn't report errors back to the user

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#24]
Log in as an admin then Settings > Email 
- change port to 8000 (or anything)
- click save

The request runs for a while then timeout happens but nothing is reported to the user. 

How about: 
- Continue to report status to the user since this operation may take awhile
- Report errors back to user 

In addition looks like once email settings are persisted next time the page is loaded the saved settings are not properly reflected.

**Comment by rmmayo** [comment]
verified.  note the error occurs when you choose a non-SMTP port that is already up an listening (like 443) - it will not error if you choose a port not already listening
