### ISSUE TITLE
when editing a skill if there are no quizzes available, the link in the no-options drop-down doesn't tab navigate properly

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#2408]
once you `tab` into the`Quizzes and Surveys`  link in the no-options drop-down, the drown-down closes making it very difficult if not impossible to click.  When you do it with screen reader enabled, after the drop-down closes, the next time you hit `tab` it brings you right back into the drop-down instead of moving to the description editor which will cause a cycle unless you change the type from `Quiz/Survey` to something else.

![image](https://github.com/NationalSecurityAgency/skills-service/assets/47030042/ac481f01-f5e1-49da-9dba-b75cacb4e53e)

**Comment by rmmayo** [comment]
PR: #2409

**Comment by dwalizer** [comment]
:+1:
