### ISSUE TITLE
Update the dashboard project to reference learning path instead of dependencies

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#2438]
There are still numerous parts of the dashboard / Inception project that reference Dependencies instead of the Learning Path.  These should be updated to be more clear.

**Comment by dwalizer** [comment]
PR #2445

**Comment by sudo-may** [comment]
looks like some of the Inception's descriptions are still using "dependency" terminology (should be changed to prerequisites)
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/a1e394c7-17a9-4a75-8f72-ff01807d126d)

**Comment by sudo-may** [comment]
:+1:
