### ISSUE TITLE
Some dependency skills are broken

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#2439]
`Visit Project Dependencies` - works
`Visit Skill Dependencies` - no longer needed
`Create Skill Dependencies` - broken
`Create Cross Project Skill Dependencies` - probably also broken

These need to be fixed or removed as applicable.

**Comment by dwalizer** [comment]
PR #2445

**Comment by sudo-may** [comment]
works but looks like some of the descriptions are still using "dependency" terminology which should be changed to prerequisites 
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/a1e394c7-17a9-4a75-8f72-ff01807d126d)

**Comment by sudo-may** [comment]
:+1:
