### ISSUE TITLE
Remove tracking of "Skill Events" reporting from Admin Activity

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2441]
Report "Skill Events" item is saved in Admin Activity when a project admin is reporting events for another user; that can however happen programatically through REST endpoint and therefore should not be documented in the admin's activity; as a part of this ticket add DB migration to remove any existing "Skill Events" item in the admin activity table

**Comment by rmmayo** [comment]
PR: #2448

**Comment by sudo-may** [comment]
:+1:
