### ISSUE TITLE
Transition Users page vue-table-2 table to use bootstrap-vue table

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#249]
Transition Users page vue-table-2 table to use bootstrap-vue table

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/254

**Comment by rmmayo** [comment]
When changing the sort order, the column sizes can jump fairly significantly if the # of chars of the values in the columns have different lengths.  Is this ok, or do we want to have a fixed column size?  I verified that the previous vue-table-2 version had the same behavior.  Screen shot below shows the differences:

![image](https://user-images.githubusercontent.com/47030042/104767578-68a07d00-573a-11eb-8a85-d4da47f5ce46.png)

![image](https://user-images.githubusercontent.com/47030042/104767640-7ce47a00-573a-11eb-9f49-cde743551583.png)

**Comment by sudo-may** [comment]
@rmmayo upon our further discussion fixed columns will make resizing process unpleasant and most of the time user name will be about the same width so we decided to keep it as-is
