### ISSUE TITLE
Validation of `Contact Users` breaks the page 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2507]
- configure `skills.config.ui.paragraphValidationRegex`
- Navigate to project's `Contact Users` page
- Add all users
- Enter invalid text that violates the validator into the Email body
- Highlight the text and delete it
- Goes to the error page

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2508

**Comment by rmmayo** [comment]
:+1:
