### ISSUE TITLE
When `Rank Opt-Out for ALL Admins` option is enabled Leaderboard's "10 around me" option always fails to load

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2521]
On Admin side: 
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/8b5c04e2-f5a6-4a13-90fc-f039abe1ce42)

On Skills Display side for non-admin user:
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/ef149abd-d27b-492d-8c7a-e4c6491b35cb)

**Comment by ACRavelo** [comment]
Containers
