### ISSUE TITLE
Error occurs when removing a Quiz Administrator in PKI mode

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#2553]

**Comment by ACRavelo** [comment]
Physical hardware at the node level.

**Comment by rmmayo** [comment]
PR: #2554

**Comment by ACRavelo** [comment]
https://www.microsoft.com/en-us/industry/microsoft-in-business/business-transformation/2022/05/04/eliminating-data-silos-to-support-value-based-care/

**Comment by ACRavelo** [comment]
Network all of the silos.
