### ISSUE TITLE
Improve ability to delete performed skill events in bulk

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#2556]
Currently, Project administrators have the ability to remove individual skill events or all of the skill events at once.  Add the ability to delete large amounts of performed skills at once without deleting all events for a user.  One idea is to add a check box to the Performed Skills table allowing Admins to select multiple rows and then delete them all at once.  

see: https://skilltreeplatform.dev/dashboard/user-guide/users.html#performed-skills

**Comment by sudo-may** [comment]
Ran into an issue while testing: if the deleted skill(s) have an error an alert is displayed (in this case the error was `You cannot delete a skill event when a parent skill dependency has already been performed.`) After some amount of seconds the alert then disappears. Any further failures to the deletes are not shown and it silently fails. Suggesting the following improvements: 
- The alert should not go away on its own and remain visible while allowing user to close the alert. 
- Any further errors should update the alert. 
- Any action (delete, filter, reset) should clear the alert

**Comment by sudo-may** [comment]
:+1:
