### ISSUE TITLE
migrate to cy.intercept in `subjects_spec.upload custom icon()`

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#256]
need to wait for https://github.com/cypress-io/cypress/issues/1647 to merged and released

**Comment by mosefer** [comment]
removing milestone, according to code comments, this ticket is waiting on https://github.com/cypress-io/cypress/issues/1647 which has yet to be completed.

**Comment by sudo-may** [comment]
obe
