### ISSUE TITLE
Videos that are slow to download seem as if they're broken

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#2560]
If a video takes a long time to download, the loading spinner just spins indefinitely with no indication to the user as to what's going on - this makes it seem like the video doesn't work, when in fact it needs to download the entire video to start playing.  Investigate if enabling the video player to stream content is feasible

**Comment by dwalizer** [comment]
Likely resolved by the switch to allowing partial content

**Comment by sudo-may** [comment]
:+1: was in fact resolved via #2563
