### ISSUE TITLE
Vue 3 upgrade - some components get focus twice on tab

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#2631]
Certain components get focused on twice when tabbing through the application.  This is potentially because of SkillsButton components being wrapped by router-link components.

Examples:
1. Level component in the header
2. Manage button on Project cards
3. Preview button for projects
4. Configure button on Self Report page
5. Achievements, subjects, skills buttons on the Metrics page (both the top and bottom buttons)

**Comment by sudo-may** [comment]
Testing results: The ticket does address components/pages mentioned in the description but there are  a number of buttons in the SkillsDisplay that also exhibit the same issue: 
- My Rank `View` Button
- My Badges `View` Button
- Subject's `View` Button
- `Learn More` Button on skill page

**Comment by sudo-may** [comment]
:+1:
