### ISSUE TITLE
Miscellaneous System Settings bugs

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#2643]
- Project preferences - Default Home Page label is not read out by the screen reader
- Strange bug - Settings -> Preferences is reading the wrong message on save; going to the Share skill with another project table and then go to Settings, Preferences, change something and Save - reads out the Share message again instead of Save message
- Text of Delete confirmation window message is not read out - title and "Yes, Delete It" button are
- Email Settings page has errors at the start, screen reader reads the first error
- Enter on the Test button, if there's an error, seems to cause focus to go back a few steps as next tab goes to field before error message

**Comment by rmmayo** [comment]
:+1:
