### ISSUE TITLE
Implement "Page moved" to handle users existing bookmarks of Project & Ranking pages

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2653]
prior 3.0.0 Project urls in Project&Ranking pages utilized `skillsClientDisplayPath` like this:

```
/progress-and-rankings/projects/<project-id>?skillsClientDisplayPath=%2Fsubjects%2F<subj1>t%2Fskills%2F<skill-id>
```
starting in 3.0.0, the new urls will be: 
```
progress-and-rankings/projects/<project-id>/subjects/<subj-id>/skills/<skill-id>
```
catch the old url and display "Page Moved" indicating that bookmark must be updated, after N seconds redirect to the new page

**Comment by dwalizer** [comment]
PR #2691

**Comment by rmmayo** [comment]
:+1:
