### ISSUE TITLE
Number of pages are not responsive

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2654]
The following pages/components do not respond well on a small screen, but there maybe others, good opportunity to test thoroughly:

- Contact Users
- Skills Expiration History 
- Project Settings
- ADD SKILL EVENTS
- CONFIGURE VIDEO
- Skills Display: Video Progress for video self report skill

need to render properly at 400% zoom @ 1280px browser width

**Comment by dwalizer** [comment]
:+1:
