### ISSUE TITLE
Icon manager - when using tab based navigation one of the tabs doesn't visually indicate where the focus is

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2670]
using keyboard only navigation:
- start creating new badge
- tab to the icon selector and press enter
- focus is placed on `Type to filter icons`
- click `tab` - focus is placed on `Font Awesome Free` tab
- click `tab` again - it is not clear where the focus is

**Comment by dwalizer** [comment]
PR #2678

**Comment by rmmayo** [comment]
:+1:
