### ISSUE TITLE
Improve notification message when initiated from schema changes or badge enabling

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#27]
imported from Gitlab: 

When schema is muted (or badge went live) that causes level or badge achieved the messages is emitted to the client event listeners. Some of the attributes do not depict the event accurately. 

Here is an example when badge went live and caused the badge to be achieved for this user, the following notification was sent: 

```json
{
  "success": true,
  "projectId": "movies",
  "skillId": "testBadgeBadge",
  "name": "testBadge",
  "pointsEarned": 0,
  "skillApplied": true,
  "explanation": "Skill event was applied",
  "completed": [
    {
      "type": "Badge",
      "level": null,
      "id": "testBadgeBadge",
      "name": "testBadge"
    }
  ]
}
```

Few ideas/questions to improve:
- fix explanation to accurately report what happened
- skillApplied should be either null or false
- should skillId be changed?? maybe ok to remain as badgeId
- do we need to add any other attributes??

**Comment by rmmayo** [comment]
verified 

```
{
  "success": true,
  "projectId": "movies",
  "skillId": "ironmanbadgeBadge",
  "name": "iron man badge",
  "pointsEarned": 0,
  "skillApplied": true,
  "explanation": "Achieved due to a modification in the training profile (such as: skill deleted, occurrences modified, badge published, etc..)",
  "completed": [
    {
      "type": "Badge",
      "level": null,
      "id": "ironmanbadgeBadge",
      "name": "iron man badge"
    }
  ]
}
```
