### ISSUE TITLE
Dark Mode Contrast Issues

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2720]
SkillsDisplay skill's progress points: 
![image](https://github.com/user-attachments/assets/261092ed-7e5e-4cba-ad48-fac8aae610ea)

SkillsDispay skill name on skill's page
![image](https://github.com/user-attachments/assets/9e76af54-1267-43cd-9586-5a924d6d37b5)

In the justification editor of self report skills:
![image](https://github.com/user-attachments/assets/490a5ed2-13f4-497a-a2fa-b081549818ae)

x/y axis labels for Point History chart: 
![image](https://github.com/user-attachments/assets/ffe35cae-50dd-45f8-b124-afe4e1c18aca)

graph node's name: 
![image](https://github.com/user-attachments/assets/d5175245-d955-4808-9453-f0c1ba8d2ea2)

my badges label (`0 Badges`): 
![image](https://github.com/user-attachments/assets/0eb1ae3f-cd89-4747-ad84-faf9c0bcd7f7)

level breakdown axis label colors: 
![image](https://github.com/user-attachments/assets/f3047fe5-112c-4774-b58b-7294343fb87e)

apex charts download popup: 
![image](https://github.com/user-attachments/assets/a92fde07-3265-4360-a260-95e08d4a13bb)

**Comment by dwalizer** [comment]
:+1:
