### ISSUE TITLE
Client Display: 'My Badges' card is shown when an empty deactivated badge is created

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#273]
- create new project - 1 subject, 1 skill, 1 user
- navigate to Client Display and notice that there is no "My Badges" card
- create global badge
- navigate to Client Display -  "My Badges" card is shown but there are no badges to actually earn

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/280

**Comment by rmmayo** [comment]
:squid:
