### ISSUE TITLE
Rendering defects on smaller screens

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#274]
Metrics Time Window Controls: 
![image](https://user-images.githubusercontent.com/51749745/104231917-9b3a3500-541d-11eb-81b7-cc695fb0e116.png)

Skill's display of Help Url: 
![image](https://user-images.githubusercontent.com/51749745/104232251-14d22300-541e-11eb-9b6c-074ab0b78d7c.png)

**Comment by rmmayo** [comment]
🦑
