### ISSUE TITLE
Axe Violations on help menu

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#2749]
The links in the help menu (both viewed and unviewed) have contrast violations and the menu itself has landmark violation

![image](https://github.com/user-attachments/assets/b4065ece-26aa-4e81-bb8c-fb7bf8a2464c)

![image](https://github.com/user-attachments/assets/46a19d5f-ee1b-48d4-a60a-1014a3b9989a)

![image](https://github.com/user-attachments/assets/e4470a10-7c65-44a6-9f5b-13e062c88b85)

**Comment by sudo-may** [comment]
:+1:
