### ISSUE TITLE
Store all user events related to a skill id, whether applied or not

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#275]
Currently only successfully applied skill events are stored for a user. Save all events to support deeper metrics on continued skill usage after achievement.

**Comment by rmmayo** [comment]
`user_events` do not seem to be recorded when the skill being reported is not outside of the minimum time window between occurrences to receive points.

Steps to repeat:

1. Visit Iron Man Skill: https://ip-10-113-80-245.evoforge.org/projects/movies/subjects/action/skills/IronMan/addSkillEvent

2. Perform a baseline count of user_events: `select count(*) from user_events`:

![image](https://user-images.githubusercontent.com/47030042/106757083-f49d1a80-65fd-11eb-8f96-6c297f1e8c08.png)

3. Add an event for user1 for today, and then refresh the count:
![image](https://user-images.githubusercontent.com/47030042/106757202-126a7f80-65fe-11eb-8d5e-61b1623300d6.png)
![image](https://user-images.githubusercontent.com/47030042/106757267-231af580-65fe-11eb-9815-413926d26c8a.png)


4. Add an event for user1 for the same day, and then refresh the count:
![image](https://user-images.githubusercontent.com/47030042/106757428-5493c100-65fe-11eb-8b1c-2a3cab74332e.png)
![image](https://user-images.githubusercontent.com/47030042/106757497-68d7be00-65fe-11eb-82ef-8014a5a567b6.png)


Note: if the skill has already been achieved (vs. not being outside the minimum time window), then the `user_event` does seem to added as expected.

**Comment by rmmayo** [comment]
spoke with @mosefer - the test above was invalid.  There is a count column that *is* being incremented even if the reported event is not outside of the minimum time window:

![image](https://user-images.githubusercontent.com/47030042/106759042-4181f080-6600-11eb-9255-d780af368ab8.png)
