### ISSUE TITLE
SkillsDisplay theme: skills filter's value color on hover is too light when only `textPrimaryColor` is configured 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2758]
take theme object of 
```
textPrimaryColor:'black'
```
the value on hover is not easily visible: 
![image](https://github.com/user-attachments/assets/5d3935d4-b011-40a1-ab47-99a8aae7dfd5)

**Comment by rmmayo** [comment]
:+1:
