### ISSUE TITLE
Export users' project achievements

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2769]
on `/administrator/projects/<project-id>/metrics/achievements` add ability to export users' achievements to csv or excel; export the following data/columns:
- user id
- user name
- user tag (if configured)
- achievement type
- achievement name
- level (if applicable)
- achievement date in GMT

**Comment by rmmayo** [comment]
PR: #2834

**Comment by sudo-may** [comment]
:+1:
