### ISSUE TITLE
Limit access to the admin portion of the dashboard

### ISSUE THREAD

**Issue by mvarblow** [NationalSecurityAgency/skills-service#2785]
We've just started using the skills service. It's a really nice application. Thanks for making it available and maintaining it. Here's an idea that would be really helpful for our use of the skills service...

We'd like all our users to be able to participate in the training, but don't want **all** users to be able to create new projects or otherwise add new training content. Could the Dashboard root users be allowed to (optionally) configure a limited list of users that are allowed to use/visit the admin portion of the Dashboard - this way admin pages can be hidden from the rest of the users.

**Comment by sudo-may** [comment]
PR https://github.com/NationalSecurityAgency/skills-service/pull/2828

**Comment by rmmayo** [comment]
:+1:
