### ISSUE TITLE
Insufficient Point warning flashes on load

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2796]
Looks like there is a race condition as the warning is shown if endpoint that provides total points did not return in-time; once the endpoint provides result the warning goes away; the warning should not be shown before the data is fully loaded

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2797

**Comment by dwalizer** [comment]
:+1:
