### ISSUE TITLE
Format Total Rows number of Users table

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2808]
on `/administrator/projects/<proj-id>/users`

![image](https://github.com/user-attachments/assets/50c948d1-6d18-4e55-a70e-c7b26110fbfa)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2839

**Comment by dwalizer** [comment]
:+1:
