### ISSUE TITLE
Dark Mode issues

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2812]
![image](https://github.com/user-attachments/assets/3a04fe83-3ce6-4968-92ad-082b1fa026f6)

![image](https://github.com/user-attachments/assets/d92ea0d6-1d93-40cd-93ec-ebf859b5019b)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2842

**Comment by rmmayo** [comment]
:+1:
