### ISSUE TITLE
Skills Display - Project Levels on Global Badge Details are always at 0%

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#2838]
![image](https://github.com/user-attachments/assets/d0c9f06a-97b6-4680-8d23-e86261dafedf)

**Comment by sudo-may** [comment]
It looks like overall progress is not updated as well:
![image](https://github.com/user-attachments/assets/dc415a36-6677-4618-949a-225aa57f8477)

**Comment by rmmayo** [comment]
PR: #2840
