### ISSUE TITLE
Custom icon are not shown/loaded for badge on `/progress-and-rankings/my-badges`

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2844]
- Create a project with a badge; configure a custom icon on that badge; make sure the badge is `live`
- Add this badge to the Project Catalog; add that project to `My Projects`
- Load `/progress-and-rankings` page then click on `My Badges` button; note that custom icon didn't load
- Refresh while on `/progress-and-rankings/my-badges`; note that icon is still not loaded
- Click on 'View Details' for that badge; custom icon is loaded; navigate back and custom icon is now displayed

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2859

**Comment by rmmayo** [comment]
:+1:
