### ISSUE TITLE
On Configure Video page - after selecting video to upload the button above upload is incorrect

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2845]
please note the button above the upload input box:
![image](https://github.com/user-attachments/assets/3f9a3e6d-8781-4294-adab-cb906c55ea2f)

same issue happens when you attempt to upload unsupported video type

**Comment by rmmayo** [comment]
PR: #2865

**Comment by sudo-may** [comment]
:+1:
