### ISSUE TITLE
custom icon is not shown after it was added by editing an existing subject 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2856]
- create a subject with default icon
- drill down into the subject page (`/administrator/projects/<project-id>/subjects/<subject-id>`)
- edit subject and set a custom icon; then save
- click edit subject again and note that custom icon is not shown

**Comment by dwalizer** [comment]
PR #2872

**Comment by sudo-may** [comment]
:+1:
