### ISSUE TITLE
Some tables do not properly resize

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2858]
Skills Table does not properly resize when optional fields are added:
![image](https://github.com/user-attachments/assets/f5c80f94-9e28-4f20-a109-ceb6a4ceaa75)

Admin Activity table doesn't properly resize:
![image](https://github.com/user-attachments/assets/22645b22-f58b-4913-bcc4-a27b3b25e5b4)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2864

**Comment by rmmayo** [comment]
:+1:
