### ISSUE TITLE
improve responsiveness to smaller screens on select pages

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2874]
![image](https://github.com/user-attachments/assets/76a6dba8-cade-496f-9fa4-b484e5f02c0b)

**Comment by sudo-may** [comment]
![image](https://github.com/user-attachments/assets/5e5f893c-ce53-49f1-88d3-83111523af8a)

**Comment by dwalizer** [comment]
:+1:
