### ISSUE TITLE
Skills table Additional Fields do no properly resize at 400% zoom

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2878]
- create at least 1 skill
- navigate to `/administrator/projects/<proj-id>/subjects/<subj-id>`
- resize browser window to 1280px width
- zoom to 400%

![image](https://github.com/user-attachments/assets/bc65b957-a9c5-4390-ad3a-a39bfa7db03b)
please note horizontal scroll appears

**Comment by dwalizer** [comment]
:+1:

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2879
