### ISSUE TITLE
Metrics graphs have issues in dark mode

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#2885]
The metrics graphs at `administrator/metrics` don't display well in dark mode; some of the labels use darker text, and the pop up when hovering over the data has white text on a light background, making it hard to read.

**Comment by sudo-may** [comment]
Looks like `Number of users for each level for each subject` and `Number of users for each level over time` charts on the `/administrator/projects/<proj-id>/metrics/subjects` page has the same issue

**Comment by rmmayo** [comment]
PR: #2891

**Comment by rmmayo** [comment]
PR 2: #2905

**Comment by sudo-may** [comment]
:+1:
