### ISSUE TITLE
Configure Approval Workload table won't show the last page

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#2889]
The last page gives incorrect information and always shows the following (when there is more than one page to view) :

![image](https://github.com/user-attachments/assets/37c504fa-e475-43b1-92a4-871d4b0d23d4)

**Comment by rmmayo** [comment]
Also, the previously selected sort order and direction are not being properly remembered and displayed when changing, navigating away, and then coming back.  This is true for the `Approvers` column, possible others as well

**Comment by sudo-may** [comment]
:+1:
