### ISSUE TITLE
Display user's quite and survey attempts on progress & ranking pages

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2933]
- display table of quizzes/surveys
- allow to drill down into a single quiz/survey to see all of its details
- create a new cards on P&R page to link to the quiz/survey attempt page
- if associated to a skill then provide a way to navigate from a skill to its attempts

**Comment by rmmayo** [comment]
wording on ticket is OBE.  Was decided not to do this:
> if associated to a skill then provide a way to navigate from a skill to its attempts

**Comment by rmmayo** [comment]
:+1:
