### ISSUE TITLE
Support focus outlines in forced-colors mode

### ISSUE THREAD

**Issue by dwalizer** [NationalSecurityAgency/skills-service#2947]
When using forced-colors mode (i.e. high contrast in Windows), the outlines are not visible.  Add the following styling to resolve this:

```
@media (forced-colors: active) {
    :focus {
        outline: 2px solid transparent;
    }
}
```

**Comment by dwalizer** [comment]
This can be tested in Chrome by using the Rendering view in Devtools.

1. Open DevTools
2. Hit CTRL+SHIFT+P
3. Search "render"
4. Click "Show Rendering"
5. In the Rendering draw, scroll to "Emulate CSS media feature forced-colors" and set to `forced-colors: active`
6. Tab around the application to verify the highlighting is still there

**Comment by rmmayo** [comment]
:+1:
