### ISSUE TITLE
Improve validation when adding local users that are already part of an Admin Group of this project/quiz

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2964]
If a given user is already part of an admin group which is assigned to a project/quize, then do not allow to add that user as a local admin/approver in the Access page of a project/quiz; display an error message, something like "User is already part of an Admin Group and cannot be added as a local admin"; validate on UI and backend

**Comment by rmmayo** [comment]
PR: #2977

**Comment by sudo-may** [comment]
:+1:
