### ISSUE TITLE
Number of quiz questions presented to use is incorrect

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#2969]
If the # of Questions per Quiz Attempt is less than the total # of questions (eg, 10 questions, but configured for only 1 per attempt), then when the user attempts to take the quiz the wording will say the quiz has 10 questions even though the user is only presented with one.

> Pass the 10-quetsion <quiz name> Quiz and earn <###>  points

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2976
