### ISSUE TITLE
Validation for enabling project community could fail when an Admin Group is assigned to it

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2986]
- Create a non-community project group and add at least 1 member/admin to it so there are 2+ admin/members in that group
- Assign the new group to a non-community project
- Try to elevate project's community to the protected status

The follow error happens for `/admin/projects/<project-id>/validateEnablingCommunity` endpoint:
```
org.springframework.dao.IncorrectResultSizeDataAccessException: Query did not return a unique result: 2 results were returned
	at skills.services.admin.UserCommunityService.validateProjectForCommunity(UserCommunityService.groovy:167) ~[!/:3.2.0-SNAPSHOT]
```

**Comment by rmmayo** [comment]
PR: #2989

**Comment by sudo-may** [comment]
:+1:
