### ISSUE TITLE
console error showing in chrome devtools when loading the dashboard

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#299]
![image](https://user-images.githubusercontent.com/47030042/106309815-a91af300-6230-11eb-921b-4fb30ae5baa6.png)

**Comment by mosefer** [comment]
@rmmayo  - I think this issue may be OBE, I can't seem to reproduce.

**Comment by rmmayo** [comment]
this appears to be a caching issue - only happens for me when using chrome in my current dev env.  No errors when using a fresh incognito chrome window.

**Comment by rmmayo** [comment]
note: confirmed this error was coming from the "axe DevTools - Web Accessibility Testing" chrome extension
