### ISSUE TITLE
Docker manifest not found

### ISSUE THREAD

**Issue by joanmdavis** [NationalSecurityAgency/skills-service#300]
I'm trying to install the SkillTree service using the [Docker-based install instructions](https://code.nsa.gov/skills-docs/dashboard/install-guide/quickStart.html#_2-install-start-dashboard-and-service). When I run `docker run --name skills-service -d -p 8080:8080 skilltree/skills-service`, I receive this error message: 

> docker: Error response from daemon: manifest for skilltree/skills-service:latest not found: manifest unknown: manifest unknown.

Could there be an issue with the container, or does the problem lie with me? :-)  I'm new to Docker. I'm installed Docker Desktop on Windows 10, and I was able to run the `hello-world`  and `ubuntu`  containers successfully, but I don't know how to resolve the SkillTree manifest error. 

I'm looking forward to using SkillTree, and I appreciate any help.

Thank you!

Joan

**Comment by sudo-may** [comment]
@joanmdavis Great to hear from you! We currently do not support ``latest`` docker tag (by design) so you'll need to specify the version explicitly - the latest version is 1.3.1 so it would look like this: 

```
docker run --name skills-service -d -p 8080:8080 skilltree/skills-service:1.3.1
```

We should however add a note in the docs to help remove this hurtle.

Hope this helps!

**Comment by joanmdavis** [comment]
Thank you, @sudo-may! Before I saw your response, I forged ahead with the Java option. The new command for the Docker installation works now, too.

**Comment by its-a-lisa-at-work** [comment]
Thanks, I found this really helpful too since I'm new to docker and I got stuck with this as well
