### ISSUE TITLE
Improve terminology of Quiz/Survey Choice questions

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#3036]
Proposed new terminology: 

- Multiple Choice: A single correct answer
- Multiple Answers: Two or more correct answers

Fix `Check one or more correct answer(s) on the left:` for both question types:
![image](https://github.com/user-attachments/assets/2060c7cf-6163-458c-a97a-0d5021f31be6)

![image](https://github.com/user-attachments/assets/873c1d47-93ba-497c-a9a2-e0999edd7e74)

**Comment by dwalizer** [comment]
:+1:
