### ISSUE TITLE
zeroFillGaps not working properly when returned User Events from UserEventService

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#305]
...at least for multiple projects, see screen shot below:

![image](https://user-images.githubusercontent.com/47030042/106620321-75e1a800-653f-11eb-8c64-4a8ba655c57f.png)

**Comment by rmmayo** [comment]
cjmoses
12:30 PM
I think because there's a single result set being returned, the code would have to zero fill from start each separate project's data and then add all of that to a single result set. I suspect it would require keeping a map of DayCountItems per projectId and only merging them into a single collection after all zero filling has taken place.

**Comment by sudo-may** [comment]
:+1:
