### ISSUE TITLE
Add support for a generic application-wide header and footer in the dashboard

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#32]
Support generic application-wide header and footer in the dashboard
- once header and footer is configured they will render on very page of the dashboard application
- only SkillTree dashboard admins will be able to configure these items
- add ability to input html for header, footer and associated styles on the Global Settings page (``/settings``)
  - design idea: have 3 input boxes: header that takes html, footer that takes html, css that applies to header and footer
  - design idea #2: 2 input boxes that will have inline styles
- Consider creating new ``Navigation item`` on ``/settings`` page (especially if we go with three input boxes)
- Validate that ``<script>`` tab is NOT supplied (both client and server)
- Implement extensive Cypress Tests and applicable backend integration tests

**Comment by mosefer** [comment]
Looks like we'll need to stick with inline css. Vue doesn't support injecting scoped styles dynamically as styles in the vue component are processed at build time.

**Comment by rmmayo** [comment]
tested

**Comment by rmmayo** [comment]
tested with more realistic header and failed.  current settings value column is varchar(255) which will need to be changed.

**Comment by rmmayo** [comment]
new ticket created to support values > 255 character - see #37
