### ISSUE TITLE
As part of CI build docker image based on the ``-SNAPSHOT`` jar and publish it to DockerHub

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#33]
As part of CI build docker image based on the ``-SNAPSHOT`` jar and publish it to DockerHub
- tag image with maven versions (ex. 1.2.0-SNAPSHOT)
- make sure to NOT assign the latest tag to it
- only keep 3 days worth of snapshots (configurable?)

**Comment by mosefer** [comment]
publish image as skills-service-ci to keep clearly separated from released versions

**Comment by mosefer** [comment]
as per discussions with sudo-may, instead of skills-service:version-snapshot, we are pushing a separate skills-service-ci image.

**Comment by rmmayo** [comment]
verified [image](https://hub.docker.com/r/skilltree/skills-service-ci)!  latest tag is present, but that is obe now that it was decided to pubish to a separate skills-service-ci repo.

also, note that this image is not showing up (as of now) when doing a [search for "skilltree"](https://hub.docker.com/search?q=skilltree&type=image), but that may be b/c it was so recently published?
