### ISSUE TITLE
Logically handle existing approval requests when self reporting type is modified

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#332]
1. Self reporting type is changed to 'Honor System' - approve all of the pending requests
2. self reporting type changed to 'Disabled' - delete all of the pending requests

In both scenarios warn an admin about what action is to be taken

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/342

**Comment by mosefer** [comment]
Attempting to submit a self reported skill event from the client-display with an empty message (which is denoted as optional), results in a 500 response.

Attempting to remove self reporting from a skill with a pending approval request results in an error in the dashboard.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/388 to address test failures as pointed out by @mosefer
