### ISSUE TITLE
Use "My Progress" page as the main landing page

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#337]
==============

- Change Logo to add a "stamp" (or some other text below maybe) for "Admin Only" view (also possibly move skills-level next to admin logo)
- Change drop down link from "Admin" to "Project Admin"
- Don't show skills-level component on "Progress and Ranking" view

===================================
- When visiting "Progress and Ranking" view 

	If no projects have been created at all:
	 - display message: No SkillTree projects have been created.  SkillTree projects can be created from the "Project Admin" view located in the drop down in the top-right.

	If no projects with "Production Mode" enabled 
	- display message: No projects with production mode enabled, once project(s) have been marked as production you will see you SkillTree progress and rankings on this page.

**Comment by rmmayo** [comment]
PR: #350

**Comment by mosefer** [comment]
@rmmayo - this feature does not have a corresponding test in [accessibility_spec.js](https://github.com/NationalSecurityAgency/skills-service/blob/master/e2e-tests/cypress/integration/accessibility_specs.js), since it's a new view it needs to be represented there.
