### ISSUE TITLE
inconsistent height for project cards on My Progress page when using Fire Fox

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#351]
```	
dimay
7:32 AM

if i make it small f5 then make it bigger it works
but if i make it big then f5 that happens
in FF
```
![image](https://user-images.githubusercontent.com/47030042/108711932-0890b980-74e4-11eb-849a-8a1089ecce24.png)

![image](https://user-images.githubusercontent.com/47030042/108711896-ff9fe800-74e3-11eb-8a17-736672c2dcfb.png)

**Comment by rmmayo** [comment]
PR: #360

**Comment by sudo-may** [comment]
:+1:
