### ISSUE TITLE
Improve looks and resizing of Post Achievement metrics

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#354]
- Change ``Post Achievement User Counts`` bar chart to take full width on ``-md`` breakpoint
- Add vertical margin between cards when each card takes 100% of the width
- 'Post Achievement Usage' chart should show a message when there is no data
- Experiment with reducing length of titles and series names, ideas:
  - Wrap post achievement charts in a card with title "Post Achievement Metrics"
  - Change chart titles to just "User Counts" and "Usage"
  - Change series for "User Counts" to "Stopped After Achieving" and "Performed at least once after achieving" or maybe just "Continued using"?
  - Maybe also add a footer to the card that wraps these 2 charts, the footer can say something like: "** Post Achievement Metrics only account for users that have fully achieved this skill".

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/369

**Comment by rmmayo** [comment]
:+1:
