### ISSUE TITLE
Zero Fill is not padding the last day 

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#358]
If the dataset has no events, then zero's are populated for all but the last day:

![image](https://user-images.githubusercontent.com/47030042/108887467-4a029100-75d8-11eb-905d-ab54037b6cc4.png)
 in the above example, the current day is `23 Feb` but the data set stops at `22 Feb`

![image](https://user-images.githubusercontent.com/47030042/108887623-7d452000-75d8-11eb-8ed4-075fc7494a77.png)
in the above example, `test` project's data set stops at `22 Feb`, but `TV Shows` project's data set goes until `23 Feb` (presumably because it has at least one non-zero event returned from the database)

To reproduce:

1. Create a project
2. Go to Admin -> Project Settings, and enable "Production Mode" (no events should be reported for the current user)
3. View the "Progress and Rankings" page by clicking on the `Home` link in the breadcrumb bar.

**Comment by sudo-may** [comment]
:+1:
