### ISSUE TITLE
Bug in zero filling applied skill events dataset

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#380]

**Comment by rmmayo** [comment]
@cjmoses - it looks like everything works properly with the default 30 days of history, but the problem still exists if time filter is set to 6 months or 1 year.  

To reproduce, login to integration as dimay and change time to 6 months or 1 year.

![image](https://user-images.githubusercontent.com/47030042/110124559-3d2c2d00-7d90-11eb-9645-cab24c3227d9.png)
