### ISSUE TITLE
Allow home/landing page to be user preference

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#383]
allow user's to choose between `Progress and Rankings` or `Project Administrator` page for their landing page.  Default will be `Progress and Rankings`

**Comment by mosefer** [comment]
PR #386

**Comment by mosefer** [comment]
With landing page preferences there is now a console error from vue-router:
```Unhandled promise rejection Error: "Redirected when going from "/skills-login" to "/" via a navigation guard."```

**Comment by rmmayo** [comment]
> With landing page preferences there is now a console error from vue-router:
> `Unhandled promise rejection Error: "Redirected when going from "/skills-login" to "/" via a navigation guard."`
> 
> #252 addresses a similar problem for client-display

@mosefer  -  having trouble re-creating...can you please provide the steps to cause the error?  thanks!

**Comment by rmmayo** [comment]
@mosefer  -  I recreated it - thanks

**Comment by rmmayo** [comment]
@cjmoses - I created a separate ticket (#392) for the un-handled redirect error.
