### ISSUE TITLE
Add optional custom footer and header to the email

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#420]
Add ability to configure custom footer and header for emails
- must be able to configure header/footer as an html as well as plain text
- store configs as settings in DB
- Add new panel/card under ``Settings -> Email Settings`` for root users

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/426

**Comment by rmmayo** [comment]
@mosefer configured email header and footer and tried sending both password reset email and skill approval email but neither of those emails had the custom header/footer present.

**Comment by rmmayo** [comment]
:+1:
