### ISSUE TITLE
referencing undefined property in clientVersionInterceptor.js

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#427]
this happens when refreshing a page after when the user is not logged in (session has expired

![image](https://user-images.githubusercontent.com/47030042/111819066-4bad3500-88b6-11eb-857c-f2e6e8181ee7.png)

**Comment by mosefer** [comment]
testing notes: 
This issue can be reproduced locally by setting the server.servlet.session.timeout property to a small number (defaults to seconds if no unit is included in the value specified)

**Comment by rmmayo** [comment]
:+1:
