### ISSUE TITLE
Skills Display theme menu background should respect the configure background color

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#439]
Skills Display theme menu background should respect the configure background color

![image](https://user-images.githubusercontent.com/51749745/112198954-09506480-8be4-11eb-9bcd-48ef8d239606.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/440

**Comment by mosefer** [comment]
:+1:
