### ISSUE TITLE
Breadcrumb navigation broken from Project Metrics view

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#442]
Attempting to navigate back to the project view using the bread crumb navigtion when in the Project Metrics view results in an error.
![image](https://user-images.githubusercontent.com/61209506/112313931-cd1e1200-8c7e-11eb-8902-f7925933a107.png)

**Comment by rmmayo** [comment]
@cjmoses - problem still seems to be happening on integration.   :-(

**Comment by rmmayo** [comment]
looks like it was a caching issue on my end.  Ctrl-Shift-R and now things a working as expected.  :+1:
