### ISSUE TITLE
Bug in zero filling applied skill events data set on Skill Events chart

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#445]
![image](https://user-images.githubusercontent.com/61209506/112376614-0d9b8100-8cbb-11eb-8d5d-ea036501faa5.png)

**Comment by rmmayo** [comment]
looks an older docker container was used.  the latest CI container looks good.

![image](https://user-images.githubusercontent.com/47030042/112469740-331e9e00-8d40-11eb-8d62-ac25de229788.png)
![image](https://user-images.githubusercontent.com/47030042/112469812-4893c800-8d40-11eb-80ba-c8fd96886a5a.png)
