### ISSUE TITLE
Project stat cards have inconsistent widths

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#447]
![image](https://user-images.githubusercontent.com/61209506/112473474-ca85f000-8d44-11eb-9133-5d7a15101c62.png)

info cards are also varying widths and should probably be a fixed width

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/453

**Comment by rmmayo** [comment]
:+1:
