### ISSUE TITLE
Gracefully handle 404 Not Found

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#454]
In this release administrative pages moved under ``/administrator`` route; let's gracefully handle users visiting older routes by redirecting them to a page with explanation

1. add new page to specifically handle ``404 Not Found`` - let user know that this page does not exist and give a link to go home
2. check for older routes and offer a redirect OR add a custom message; routes to check: ``/projects``, ``/globalBadges`` and ``/metrics``

**Comment by rmmayo** [comment]
:+1:
