### ISSUE TITLE
Self Report approval table displays ``userId`` rather than ``userIdForDisplay``

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#487]

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/489

**Comment by mosefer** [comment]
Still showing userId for me:
![image](https://user-images.githubusercontent.com/61209506/114042726-ad2c4800-9853-11eb-96db-3fd636cb5819.png)

![image](https://user-images.githubusercontent.com/61209506/114042810-c03f1800-9853-11eb-8ecf-e010a1dcbc2d.png)

**Comment by mosefer** [comment]
:+1:
