### ISSUE TITLE
``Achievements over time`` and ``Skill events`` charts on the skill page do not have zoom controls

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#494]
``Achievements over time`` and ``Skill events`` charts on the skill page do not have zoom controls; you can use select tool to zoom in but there is no way to zoom out without refreshing the page

**Comment by rmmayo** [comment]
note: when testing, we should make sure the controls adjust properly when changing the screen to a smaller size - I know some of the other charts with controls had issues with this that need to be addressed in this release.

**Comment by mosefer** [comment]
:+1:
