### ISSUE TITLE
Applying Filter with no Types selected results in an error in the Project Achievement browser

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#512]
![image](https://user-images.githubusercontent.com/61209506/114592721-3c24d000-9c59-11eb-860c-1b52edddf3cf.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/514

**Comment by rmmayo** [comment]
:+1:
