### ISSUE TITLE
Prominently report to the user that old client lib is being used and gently suggest to upgrade

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#535]
- show which library is used
- suggest what the latest is

**Comment by sudo-may** [comment]
After further evaluation it was decided to utilize Dashboard's ``Issues`` page. 
- During the build discover the latest version of the client-lib by locating the version of ``@skilltree/skills-client-vue`` configured in the ``dashboard/package.json``; if possible that version should make it into spring boot's configuration (mvn magic?) and then injected into a Spring's component/service
- if the latest version and reported version doesn't match add an entry in the ``project_error`` table; make sure errors are normalized per lib's version - ``last_seen`` and ``count`` columns are updated

**Comment by dwalizer** [comment]
PR #1531

**Comment by rmmayo** [comment]
:+1:
