### ISSUE TITLE
Improve admin's projects page display and latency to better handle many projects per user

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#539]
some users may select to create a large amount of projects, improve display and latency when admins create 30+ projects

**Comment by mosefer** [comment]
some improvements to project loading queries done as part of #525 - once those changes are merged, this ticket should evaluate whether or not project level settings should be loaded for the /projects page.

**Comment by rmmayo** [comment]
PR: #638 

some changes also previously merged under PR: #634
