### ISSUE TITLE
How to get auth token which i can interally use in my application for api calls?

### ISSUE THREAD

**Issue by TEJAPS** [NationalSecurityAgency/skills-service#594]
Hi team,

I have client-id and client-secret, But I am not able to get token for it, I was following this documentation: https://code.nsa.gov/skills-docs/skills-client/auth.html

For example:  I want to make an API call to this API: http://localhost:8081/api/projects
1. How should I get token
2. How should I pass token to API's

Thank you

**Comment by sudo-may** [comment]
The typical flow for the [password installation mode](https://code.nsa.gov/skills-docs/dashboard/install-guide/installModes.html#password-auth-mode) is that the client library is configured to point to an [authentication endpoint](https://code.nsa.gov/skills-docs/skills-client/auth.html#authentication-endpoint). This endpoint is implemented by you on your backend server, it interacts with SkillTree's skills-service using the project's client-id and client-secret. The SkillTree client code is configured to point to this authentication endpoint running on your backed server.

You can find a working example in in the [skills-client-examples](https://github.com/NationalSecurityAgency/skills-client-examples)
- Endpoint Example: [ControllerExample#getUserAuthToken](https://github.com/NationalSecurityAgency/skills-client-examples/blob/master/java-backend-example/src/main/java/skills/examples/ControllerExample.java)
  - This example is explained in the docs here: [Authentication Endpoint](https://code.nsa.gov/skills-docs/skills-client/auth.html)
- Client Configuration is dependent on the library but here is an example from vue.js:  [SkillsConfiguration.configure](https://github.com/NationalSecurityAgency/skills-client-examples/blob/master/vuejs-example/src/main.js)
  - Client library usage is described in the [Integration Guide](https://code.nsa.gov/skills-docs/skills-client/#client-display-integration)

[Quick Start](https://code.nsa.gov/skills-docs/dashboard/install-guide/quickStart.html) has instructions of how to run the examples code

Hope this helps and best of luck!

**Comment by TEJAPS** [comment]
so basically 
I have the backend running 

I created a project whose id is movies
and then I hit this API from postman: http://localhost:8081/api/users/tejap@gmail/token

so I should get a token already right
But instead, i get a response saying

{
    "timestamp": "2021-04-30T18:12:18.673+00:00",
    "status": 401,
    "error": "Unauthorized",
    "message": "",
    "path": "/api/users/tejap@gmail/token"
}

![image](https://user-images.githubusercontent.com/29141451/116737219-9621e580-aa0e-11eb-822f-6be993df5a17.png)

**Comment by sudo-may** [comment]
sounds like you very close to making it work! see if there are any errors in the logs of your backend server as well as the skills-service's logs

I just followed [Quick Start](https://code.nsa.gov/skills-docs/dashboard/install-guide/quickStart.html) and was able to retrieve token implemented by [ControllerExample](https://github.com/NationalSecurityAgency/skills-client-examples/blob/master/java-backend-example/src/main/java/skills/examples/ControllerExample.java)

My steps are: 

terminal 1:
``` bash
docker run --name skills-service-1.4.4 -d -p 8080:8080 skilltree/skills-service:1.4.4
java -jar ~/Downloads/java-backend-example-1.1.0.jar
```
terminal 2: 
```
$ curl http://localhost:8090/api/users/user1@email.com/token
{"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic2tpbGxzLXNlcnZpY2Utb2F1dGgiXSwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInByb3h5X3VzZXIiOiJ1c2VyMUBlbWFpbC5jb20iLCJleHAiOjE2MjAxMDY4NTgsImF1dGhvcml0aWVzIjpbIlJPTEVfVFJVU1RFRF9DTElFTlQiXSwianRpIjoiM1NXQUhweTM3SW5ZY1Uzc0VzYWt0YUdsYXk0PSIsImNsaWVudF9pZCI6Im1vdmllcyJ9.P-YyaT7SnpVW0hui9VfRuuFFYn4EW06RlzkEscArrDbPvnRCyPfsYwzqoJbE0fBKKauk805wIDK8fARUOrcmN3V3DyBbW47HyM6uay2eHCdoBPdyiTMpr_0lWikbK66qy-Fl8ORGpXZdlRlgvloLP4Kmo1WenAGNvZhNi95bMYbxxOvJh71grnXhSWXMsFyAxu3GL7HyXzC6Saud8Nawz_mhXtZJfHqfxYn4VEzwEUZ9UoxoG1w5RNZnlfAmWrsI4ITD57epTJXum9mdivAY829FQ5YFYtW1sni7Z_w2vS9tI4mRBqOmbeMYHWYUb1WzKG9-IY1FQGthLPczot15vw","token_type":"bearer","expires_in":43199,"scope":"read write","proxy_user":"user1@email.com","jti":"3SWAHpy37InYcU3sEsaktaGlay4="}
```

best of luck!

**Comment by TEJAPS** [comment]
@sudo-may thanks a lot now getting the token.
And also the dashboard panels and all is visible on running the docker image.


But what different I am doing compared to what is mentioned on the quickstart is:
1. Cloned this repo : https://github.com/NationalSecurityAgency/skills-service
2. Build/clean/install and started service present at path: https://github.com/NationalSecurityAgency/skills-service/tree/master/service which runs on 8080
3. Now when I hit localhost:8080, I get: An error happened during template parsing (template: "class path resource [templates/error.html]")

Q1. what could be the reason.

Q2. And what is the docker(present on quickstart page) running - is it internally running: https://github.com/NationalSecurityAgency/skills-service/tree/master/service
or anything else? If it's the same then why do I see this error: An error happened during template parsing (template: "class path resource [templates/error.html]")

**Comment by mosefer** [comment]
@TEJAPS once you've cloned skills-service, you need to issue ```npm run build``` in both the ```dashboard``` and ```client-display``` projects before running build/clean/install on ```service``` - the pom.xml file in ```service``` [copies those UI resources during packaging](https://github.com/NationalSecurityAgency/skills-service/blob/7eb0a8d6d561c1c3ffe04865651510ddf7858b44/service/pom.xml#L401)

**Comment by TEJAPS** [comment]
npm run build was a success on dashboard and client-display,
but clean install on service - resulting in test failures.

Step1: For time being executed given jar on quickstart and skill service is up - running on port 8080
Step2: executed the sample example backend spring boot app - it created root user with email and some items in skill service - running on port 8090

Step3: About Api's
I am hitting the backend API URL ( http://localhost:8090/api/users/bill@email.org/token ) - receiving the bearer token successfully
But I am not able to use the same token for skill service API's like ( http://localhost:8080/api/users/ with bearer token generate above as authorization header )- throwing 401. 
What's the relationship between token generated by backend and usage of it in the skill service.


Can't we generate token and make use of skill service api's without running spring boot like java-backend-example.
 As i see its not doing much apart from creating users and default projects/skills/and similar stuff.

**Comment by mosefer** [comment]
@TEJAPS  - see if the comment here helps to make anything more clear https://github.com/NationalSecurityAgency/skills-service/issues/600#issuecomment-839947719 if not, feel free to reply and we'll provide further guidance.
