### ISSUE TITLE
Preference to opt-out for rank and leaderboard on SkillsDisplay

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#612]
Add a new preference to opt-out for rank and leaderboard on SkillsDisplay
- on user preference page add ability to opt-out
- when ranking SkillsDisplay will ignore any users that opted-out
- for a given user that opted-out SkillsDisplay will clearly indicate that "you are opted-out"

Provide ability to opt-out all of the project's admins

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/617

**Comment by rmmayo** [comment]
:+1:
