### ISSUE TITLE
How hard to integrate SkillsTree Gamifiction to this Super Productivity App

### ISSUE THREAD

**Issue by cybrpimp** [NationalSecurityAgency/skills-service#622]
Hey guys,

We had lots of problems learning how to get the authentication setup and I'm still not very solid with the concept, but how hard would it be to integrate to a nice Lean [Super Productivity Desktop UI](super-productivity.com).

**Comment by cybrpimp** [comment]
@rmmayo @mosefer Hey guys, if you have time, would you mind taking a look a this issue and give me your opinion please?

**Comment by mosefer** [comment]
@cybrpimp - we're not familiar with Super Productivity Desktop UI. Giving it a quick look-over it certainly seems like integrating SkillTree into it wouldn't be too challenging however, not being experts in that tool, we wouldn't be the right ones to create a training profile for it/determine what Skills should be created.

**Comment by cybrpimp** [comment]
I would be able to help with the Training Profile & Skills.  I'm not able to help with the development side of things but can help out with other aspects.

I really seems like it would help get passed the barrier of integration that it feels like many people are struggling with.
