### ISSUE TITLE
SkillsDisplay: Back button/history entries are lost on reload for Firefox and some version of chrome

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#627]
see NationalSecurityAgency/skills-client#127

**Comment by rmmayo** [comment]
PR: #634

**Comment by rmmayo** [comment]
@sudo-may - I noticed this was still assigned to me, but I  believe it's been merged you have already tested this?  Leaving it open for now just in case.

**Comment by sudo-may** [comment]
:+1:
