### ISSUE TITLE
Improve Custom Paragraph validation to better account for markup

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#630]
custom paragraph validation should account for the start of a paragraph being the markdown bullet/numbered list character and should probably ignore those characters. See [CustomValidator.groovy](https://github.com/NationalSecurityAgency/skills-service/blob/f327cdf686da24df7d6c1d1da47e5b486de77a11/service/src/main/java/skills/services/CustomValidator.groovy#L121)

**Comment by mosefer** [comment]
This may not be an immediate concern, if the bulleted/numbered listed is not separated by an empty line from the previous paragraph, it is assumed to be part of the previous paragraph's validation.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/675

**Comment by rmmayo** [comment]
:+1:
