### ISSUE TITLE
Project card buttons overlapping name on small screens

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#642]
![image](https://user-images.githubusercontent.com/61209506/120539992-2c527e00-c3b6-11eb-9e1c-afa342a3e97c.png)

**Comment by mosefer** [comment]
It looks like this was merged in PR #655

**Comment by rmmayo** [comment]
@mosefer - seems to still be happening on integration:

![image](https://user-images.githubusercontent.com/47030042/121942435-788ab000-cd1e-11eb-9aea-42b8981ad803.png)

**Comment by mosefer** [comment]
this also impacts long project names on not-so-small screens:
![image](https://user-images.githubusercontent.com/61209506/122072124-4e3ffd80-cdc5-11eb-8004-13e53b73e625.png)

**Comment by sudo-may** [comment]
was addressed in #662
