### ISSUE TITLE
Display Subject with Badge Skill Dependencies on the client

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#643]
Currently, when viewing the client-display, a Badge's Skill dependencies do not show the Subject that the Skill belongs to. If a project (or multiple projects) have similarly named Skills this can be confusing. The Subject should be displayed along with the Skill name.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/838

**Comment by rmmayo** [comment]
:+1:
