### ISSUE TITLE
Escaped characters in help URL are replaced with non-escaped value when going back to edit

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#647]
if you enter a help URL that contains a `%20`, if you go back to edit after you saving the `%20` character is replaced with a space character ` ` and the user would have to go back and replace each space ` `  with `%20` before being able to save again.

**Comment by mosefer** [comment]
@rmmayo - cannot reproduce this

**Comment by rmmayo** [comment]
@cjmoses - it happens when editing a skill.  Subject seems to work correctly

**Comment by rmmayo** [comment]
PR: #672

**Comment by sudo-may** [comment]
:+1:
