### ISSUE TITLE
``Sign up`` link on the login page does not work when password validation triggered an error

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#650]
![image](https://user-images.githubusercontent.com/51749745/121533221-13f1ed00-c9ce-11eb-8139-3931a373d993.png)

**Comment by mosefer** [comment]
@sudo-may unable to reproduce this on integration

**Comment by sudo-may** [comment]
@mosefer neither can I now, closing this ticket
