### ISSUE TITLE
User Agreement page improvements 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#652]
User Agreement page improvements (follow on to #636): 
- remove header when user agreement is displayed; instead proposing to display SkillTree logo in the center followed by the agreement (similar to the login page look)
- add ``No Thanks`` button that will log-out this user
- wrap agreement in the border and add padding; 
- center 'Acknowledge' button
- rename 'Acknowledge' button to 'I Acknowledge'? 
- add some space between footer and the agreement
- see if User Agreement input dialog can be re-sizable (similar to email footer/header)

**Comment by rmmayo** [comment]
:+1:
