### ISSUE TITLE
"This Skill" color does not match the legend for cross-project skill dependencies in the skills-display

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#659]
Note `The Avengers`, (which is the current skill) should be light blue, but it is gray.

![image](https://user-images.githubusercontent.com/47030042/121684853-4151a000-ca8d-11eb-80cb-faea08d300ce.png)

**Comment by mosefer** [comment]
note that the "owning" skill, in this case Avengers, is also incorrectly identified as a cross-project skill for the purposes of clicking on it. If, while viewing the client-display for the project that contains The Avengers, you click on The Avengers in the dependency graph, you're presented with:
![image](https://user-images.githubusercontent.com/61209506/123113159-5377fa80-d40c-11eb-95d2-a7c1289653e5.png)

which doesn't make sense as you're already viewing the skill's project.

**Comment by mosefer** [comment]
Note that the dependency graph skill color issue only arises when there is only one dependency and that dependency is shared from another project.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/684

**Comment by rmmayo** [comment]
:+1:
