### ISSUE TITLE
Make badge card to be consistent with subject card

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#662]
should look similar to this: 

![image](https://user-images.githubusercontent.com/51749745/121735426-1c2c5400-cac4-11eb-9992-abdcc341e446.png)

See if some of the components can be generalized and re-used

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/671

**Comment by rmmayo** [comment]
:+1:
