### ISSUE TITLE
Minor display issues on a small screen on a project page

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#669]
Edit button is just an icon - looks like there is enough space to keep the word Edit:
![image](https://user-images.githubusercontent.com/51749745/122091379-b9de9680-cdd6-11eb-83e6-b9af389232f9.png)

Navigation burger icon should be right aligned:
![image](https://user-images.githubusercontent.com/51749745/122091650-0629d680-cdd7-11eb-89bd-7c8f4d09ece7.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/673

**Comment by rmmayo** [comment]
:+1:
