### ISSUE TITLE
``projects_spec.js#page header rendering on small screen`` snapshot comparison is failing 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#678]
``projects_spec.js#page header rendering on small screen`` snapshot comparison is failing 

https://dashboard.cypress.io/projects/7kivjf/runs/2416/test-results/41f1184c-196e-4d7a-8cb0-cf8a7c765cb2

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/679

**Comment by mosefer** [comment]
:+1:
