### ISSUE TITLE
Space in help url hostname still improperly handled

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#691]
#647 fixed encoded spaces in help url path and query params, however if the hostname/authority contains a percent encoded space, the percent encoding will be replaced by a space when going to edit that entity, causing the help url to fail validation until the space is once again replaced with a %20 encoding. 

pct-encoding is specifically allowed for the host component of a url as per [rfc-3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3) so we should properly handle this case.

**Comment by rmmayo** [comment]
:+1:
