### ISSUE TITLE
Editing a Global Badge causes a console error

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#692]
Editing a Global Badge and saving the edits causes a console error:
![image](https://user-images.githubusercontent.com/61209506/123448200-a7b7e180-d5a8-11eb-8fbd-5fb5d27f00ca.png)

Note that this only occurs if the badge is modified and saved. Canceling the global badge edit window or using the X button to close it, does not produce this error.

**Comment by mosefer** [comment]
Confirmed that this is unique to Global badge edits. Project Badge edits are unaffected.

**Comment by sudo-may** [comment]
:+1:
