### ISSUE TITLE
Dependency graph in Skills Display not loading correctly when loading a skill from a parent dependency

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#693]
Navigate to `/subjects/Family/skills/HarryPotterandtheChamberofSecrets/dependency/HarryPotterandthePhilosophersStone` and it will load the skill summary for the current skill (HarryPotterandthePhilosophersStone), but the dependency chart for parent the dependency (HarryPotterandtheChamberofSecrets).

![image](https://user-images.githubusercontent.com/47030042/123467288-561a5180-d5be-11eb-8235-712275a009be.png)

**Comment by rmmayo** [comment]
PR: #701

**Comment by sudo-may** [comment]
:+1:
