### ISSUE TITLE
Sorting projects in project administrator view is broken

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#695]
results in a 500 error caused by
```skills.services.ProjectSortingService.changeProjectOrder(ProjectSortingService.groovy:145)```

**Comment by mosefer** [comment]
This occurs when a root user tries to change the order of a project they did not create.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/706

**Comment by rmmayo** [comment]
@mosefer  - I deployed the latest to pki cluster.  Tried changing the sort order - no error, but the order remained the same :-1:

**Comment by rmmayo** [comment]
@mosefer  - update, when I try to move the first project, `Movies` I do receive a 500 error:

```
skills-service.0.kgpqnun2g33i@ip-10-113-80-65.evoforge.org    | 
skills-service.0.kgpqnun2g33i@ip-10-113-80-65.evoforge.org    | org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is Assertion failed: 
skills-service.0.kgpqnun2g33i@ip-10-113-80-65.evoforge.org    | 
skills-service.0.kgpqnun2g33i@ip-10-113-80-65.evoforge.org    | assert swapWith.projectId != moveMeProjectId
skills-service.0.kgpqnun2g33i@ip-10-113-80-65.evoforge.org    |        |        |         |  |
skills-service.0.kgpqnun2g33i@ip-10-113-80-65.evoforge.org    |        |        'movies'  |  'movies'
skills-service.0.kgpqnun2g33i@ip-10-113-80-65.evoforge.org    |        |                  false
skills-service.0.kgpqnun2g33i@ip-10-113-80-65.evoforge.org    |        skills.storage.model.Setting(id:7584, settingGroup:project_sort_order, projectId:movies, setting:project, value:19, userRefId:1, type:UserProject, created:2021-06-29 20:49:13.91, updated:2021-06-29 20:54:11.567, enabled:false)
```

**Comment by rmmayo** [comment]
after redeploying, sorting seems to be working except on pki-dev cluster - when pinning an additional, pre-existing project or creating a new project, that project is appended to the end of the list.  If I think try to move that project up from the bottom, nothing changes.  This same scenario works find on the oauth-dev cluster

**Comment by sudo-may** [comment]
:+1:
