### ISSUE TITLE
Top few nodes cannot be clicked

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#713]
When nodes are located on the same level as the legend they cannot be clicked; in the screenshot below the 2nd node cannot be clicked on but the 3rd one works

![image](https://user-images.githubusercontent.com/51749745/123864222-80d71380-d8f8-11eb-99e6-7ccb0819910d.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/716

**Comment by mosefer** [comment]
:+1:
