### ISSUE TITLE
Attempts to sort a newly created project when a root-user fail

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#715]
This is due to a flaw in the code that checks for a pre-existing sort setting. A sort setting is created for the user who creates the project, when an root user pins a project a sort setting is created for that user at the time. If the root user created the project a sort setting will already exist when the pin request is made. A bug in the data accessor method prevents this pre-existing setting from being returned, resulting in duplicate sort settings being created. When an attempt is made to move the display order of this newly created project, only one of those sort settings is modified, the result is inconsistent display depending on which sort setting is retrieved to determine display order when all projects are loaded.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/717

**Comment by sudo-may** [comment]
:+1:
