### ISSUE TITLE
Approval of self reported skill fails when project has insufficient points assigned

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#743]
Approval of self reported skill fails when project has insufficient points assigned:
- create a new project with 1 skill that has less than 100 points
- make that skill self reportable 
- report the skill via Skills Display 
- got the approval page and approve the skill which will cause an error page

I believe the correct thing to do is to not disable the reporting button and inform the user that skill cannot be reported due to the insufficient points. Also need to update logic to NOT add an approval request when there are insufficient points.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/754

**Comment by rmmayo** [comment]
:+1:
