### ISSUE TITLE
HttpMessageNotWritableException showing up in the logs

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#744]
It looks like there are periodic errors in the logs in response to POSTs to /skills-websocket/*
```Handling exception```
```...HttpMessageNotWritableException: No converter for [class java.util.LinkedHashMap] with preset Content-Type 'application/javascript;charset=UTF-8'```

not sure if this is benign or not.

**Comment by sudo-may** [comment]
OBE
