### ISSUE TITLE
Enable ``Manage My Projects`` button on the empty ``Progress and Ranking`` page

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#747]
Enable ``Manage My Projects`` button on the empty ``Progress and Ranking`` page; also update tool-tip to say "Click here to add to My Projects"

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/751

**Comment by rmmayo** [comment]
:+1:
