### ISSUE TITLE
Rendering issues on small screen for the project's cards on the Progress and Ranking page

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#749]
![image](https://user-images.githubusercontent.com/51749745/125960979-bbb5b120-40b0-4246-954b-fe13cff97074.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/752

**Comment by rmmayo** [comment]
:+1:
