### ISSUE TITLE
create users through api

### ISSUE THREAD

**Issue by calderaax** [NationalSecurityAgency/skills-service#772]
The endpoints available  seems to be just to repot a skill achievement. Is there any way to create users using the API dynamically.

In our case we have an education platform and we would like to integrate it with skilltree as a gamification strategy. Each time a course is finished we would like to trigger a function that looks for that user in skilltree and if it doesn't exist add it as a new account and add the skill.

Any ideas on how to implement this?

**Comment by sudo-may** [comment]
@calderaax I think there maybe is a simpler way that is already supported but correct me if I am off base here. A dashboard user with admin privileges can report skill events for any arbitrary user (user-id more accurately). [Report Skill Event Endpoint](https://code.nsa.gov/skills-docs/skills-client/endpoints.html#report-skill-event-endpoint) accepts an optional parameter ``userId``. The good news is that a dashboard account does not need to exist for a specific userId before that userId  has a skill reported via [Report Skill Event Endpoint](https://code.nsa.gov/skills-docs/skills-client/endpoints.html#report-skill-event-endpoint). In fact a dashboard account never needs to exist for that userId if the user never intends to interact with the dashboard application directly.

In your case you would create 1 skill per course and when a course is completed by a user call  [Report Skill Event Endpoint](https://code.nsa.gov/skills-docs/skills-client/endpoints.html#report-skill-event-endpoint) with the ``userId`` parameter supplied. SkillTree. The next step is to integrate [SkillTree client libraries](https://code.nsa.gov/skills-docs/skills-client/#skilltree-client-libraries) ([Skills Display](https://code.nsa.gov/skills-docs/skills-client/vuejs.html#skills-display) component) into your application which will visualize user's progress and ranking (identified by the userId)

Let me know if it works, but if not, we can discuss other approaches.

**Comment by calderaax** [comment]
oh ok great, i'll try that... yes the user is not supposed to interact with the dashboard directly. Thanks for the fast response @sudo-may i'll keep working based on your answer 👍
