### ISSUE TITLE
Using special characters in the Achievements' filters causes an error page

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#789]
Using special characters in the Achievements' filters causes an error page
- navigate to ``/administrator/projects/movies/metrics/achievements``
- type ``#`` into ``User Name Filter`` input OR into ``Name (Subject, Skill and Badge Only):``
- press enter or click ``Filter``

**Comment by rmmayo** [comment]
PR: #797

**Comment by sudo-may** [comment]
:+1:
