### ISSUE TITLE
Not Achieved Skill query produces inaccurate results

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#793]
When selecting only Not Achieved Skills for the Contact Users filters, the query only considers users with achievements who have not achieved the specified skills. This should instead consider all projects users who have not achieved the specified skills. The count of project users who have achieved a skill + the count of project users who have not achieved that skill, should be equal to the all project users count.

**Comment by sudo-may** [comment]
:+1:
