### ISSUE TITLE
When adding a new root user, the user is not shown in the 'Supervisor Users' table until refresh

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#798]
The table should reflect that the user is now a Supervisor and a Root user once added.  Currently it only shows up in the Root User's table until reloaded.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/801

**Comment by rmmayo** [comment]
:+1:
