### ISSUE TITLE
populate `userTags` when loading `UserInfo` from database

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#806]
see https://github.com/NationalSecurityAgency/skills-service/blob/master/service/src/main/java/skills/auth/UserAuthService.groovy#L85

**Comment by rmmayo** [comment]
PR: #819 

@sudo-may  - we may want to reconsider merging this ticket - when I first created the ticket  did not realize it requires an extra db lookup.  May not be worth it since we are not currently using the userTags from the UserInfo object itself (outside of storing them in the database when returned from the user-info-service)

**Comment by sudo-may** [comment]
@rmmayo I concur - let's NOT merge it
