### ISSUE TITLE
Email not configured mask on contact users pages does not fully cover component

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#811]
Contact Users:
![image](https://user-images.githubusercontent.com/61209506/130229467-2141e4a1-c347-4e7c-917e-122ce2df49fa.png)

Contact Admins:
![image](https://user-images.githubusercontent.com/61209506/130229524-7e84938a-941b-4399-9c43-bdd8510495d5.png)

**Comment by jdbaudean** [comment]
"contact users" looks good, I get "unauthorized" when I try to hit the /administrators/contactAdmins url

**Comment by rmmayo** [comment]
> "contact users" looks good, I get "unauthorized" when I try to hit the /administrators/contactAdmins url

Did you use the the link in the nav bar to get there, or did you just change the URL?

![image](https://user-images.githubusercontent.com/47030042/133599469-abee9075-bad1-4827-a088-e45afb3b7c55.png)
  
seems like you used an account without root permissions?

**Comment by jdbaudean** [comment]
Yep, using the preconfigured account did the trick.  Looks good.
