### ISSUE TITLE
Display My Projects' badges and global badges on Progress and Ranking views

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#812]
On ``Progress and Ranking`` view display add ``Badges`` button on the Badges card that would lead to the following view: 
- visualize achieved badges
- display available badges catalog
- only show badges/global badges for projects that the user added to 'My Projects'
- provide ability to view skills that are required to achieve for a badge as well as user's progress within that badge

Re-use badges views/code from client-display
- optionally include project name
- the data source would be altered to one that only returns badges/global badges for projects that the user has added to 'My Projects'

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/824

**Comment by rmmayo** [comment]
:+1:
