### ISSUE TITLE
Skills Display: Badge Search and Filter 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#815]
This will apply to both Badges view on the ``Progress and Ranking`` pages as well as ``Skills Client/Display`` pages

- Add ability to filter
  - Global Badges only
  - Project Badges only
- Add ability to search by badge's name

Re-use established search/filter methodology used in skills: 
![image](https://user-images.githubusercontent.com/51749745/131145637-2723e4e9-d272-4d0f-90dd-cfba1dabc44b.png)
Note: implement/verify themeing support (similar to skills' impl)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/845

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/859

**Comment by rmmayo** [comment]
:+1:
