### ISSUE TITLE
Removing a requirement from a Global Badge does not trigger award to newly qualified users

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#818]
Removing a level/skill requirement from a Global Badge does not trigger award of the badge to users who now qualify as they have achieved the remaining requirements.

**Comment by jdbaudean** [comment]
PR #854

**Comment by mosefer** [comment]
Kicking back - it looks like something may have been changed that impacts enabling a global badge. To reproduce:

Create a global badge that has two projects level requirements (ensure that there are users in the system who have at least a Level 1 for both projects but only meet one of the project level requirements). Enable the badge. Note that it appears that users who have L1 in both projects are awarded the badge on publishing but those users do not meet the specific level requirements. (i.e., if the badge requires L1 in Proj1 and L5 in Proj2, users who have a L1 in Proj1 and an L1 in Proj2 are awarded the badge when it is enabled).

**Comment by sudo-may** [comment]
@mosefer was this fixed in #860? should this ticket be re-tested?

**Comment by mosefer** [comment]
:+1:
