### ISSUE TITLE
Progress is not updated when points are awarded for ``honor system`` self reported skill

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#828]
When requesting ``self reported`` skills with the `` Honor System`` points are reflected within an individual skill (ex. progress bar is updated) but progress within subject and/or badge is not updated. This is only an issue when points are requested and then received (due to the ``Honor System``) on the subject or badge page:

subject page example: 
![Screenshot at 2021-09-13 11-27-21](https://user-images.githubusercontent.com/51749745/133112180-b4529261-656a-4e95-9789-241e2bb496e5.png)

badge page exampe:
![Screenshot at 2021-09-13 11-24-59](https://user-images.githubusercontent.com/51749745/133111931-6fcbcdb5-c311-44aa-8e96-ea7bec22ba98.png)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/881

**Comment by rmmayo** [comment]
:+1:
