### ISSUE TITLE
Improve self-report skills request and rejection messages

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#850]
- client-display: when reporting skills
  - change input to text - support multiple lines
  - add validation - max number of characters
- dashboard: display long messages gracefully
   - support long messages for approval requests as well as history 
- dashboard: when rejecting
  - add validation - max number of characters

**Comment by rmmayo** [comment]
:+1:

**Comment by rmmayo** [comment]
@cjmoses - I noticed that when the self report skill uses the "Honor System" that it shows the character limit warning even though there is no text area for the user to type into... we should remove the warning message for this scenario.

![image](https://user-images.githubusercontent.com/47030042/140165499-d42d00a0-5cd3-4394-9d43-e9c7617bdf42.png)

**Comment by mosefer** [comment]
Did not notice this until just now. Will be addressed in #942

**Comment by rmmayo** [comment]
:+1: see #942 for removing the warning message
