### ISSUE TITLE
Progress and Ranking: Project's title  - display project name instead of project id 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#851]
Currently project id is displayed for the title on ``/progress-and-rankings/projects/<projectId>``, for example: 

![Screenshot at 2021-09-21 11-14-47](https://user-images.githubusercontent.com/51749745/134198243-62ce32c0-7005-4606-91c1-3579f7153b2b.png)

**Comment by rmmayo** [comment]
:+1:
