### ISSUE TITLE
Global badges - add ability to modify project's level requirements

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#852]
Currently the only way to decrease/increase project level requirement within a global badge is by removing the level and then re-adding it. The problem is that when a level is removed then the badge will be awarded to any user that achieved all of the remaining requirements. 

Add a mechanism to atomically modify existing level requirement. Check for user achievements only if the level was decreased. 

UI idea, add ``Edit`` button next to the delete button: 
![Screenshot at 2021-09-21 11-29-32](https://user-images.githubusercontent.com/51749745/134200650-a2d65cea-9c48-4dd5-8e3e-d9fe21166285.png)

**Comment by mosefer** [comment]
PR #879
