### ISSUE TITLE
Skill Groups - add ability to group skills

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#853]
### Admin 
- group will have it's own name and id
- group 1 or more skills 
- 2 achievement options: (1) require achievement of all skills in a group OR (2) require N number of skills achieved (ex. 2 out of 5)
  - in case of number 2 all of the skills in the group must have the same point configuration; only points for the required number of skills will contribute to the overall points profile
- tbd: groups will *probably* need to respect skill versioning mechanism 
- tbd: groups may create an achievement record

### Skills Display
- on skills page visualize groups and their progress
- show groups skills underneath
- clearly show how many skills has to be completed to earn group's points

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/948

**Comment by mosefer** [comment]
Create a Skill Group with 3 honor system Self Report skills that requires 2 out 3 for completion. Notice that reporting the completion of one of the skills in the group through the client-display results in the incorrect display of the points achieved for that skill event (however the Skill Groups total points is correct). This is only on the client side as refreshing the view results in the correct point metrics.

It also appears that arriving at the Skill Group using the ```Self Reported Skills``` filter on the skill search box does not exhibit the above doubling, however browsing directly to the Skill Group or using the text input for the skill search box does result in the doubling of points in the specific skill metrics cards.
