### ISSUE TITLE
Global Badges show up as 100% complete but not yet achieved in client display

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#856]
In client-display -> My Badges and the My Progress -> My Badges view, Global Badges that have only Project Level requirements show up as 100% complete if the user has A level > 0 in the required Projects for the badge, but does not have the required level for all Projects. There may be other cases.

Steps to reproduce:
1. Create a Global Badge
1. Add Project Level requirements for two different projects (and no Skill requirements)
1. Create a user who has a level > 0 in both required projects but < then the required level in at least ONE of the required projects

**Comment by mosefer** [comment]
PR #871

**Comment by rmmayo** [comment]
:+1:
