### ISSUE TITLE
Global Badge Project Level dependency regression

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#860]
Publishing/enabling a global badge with only Project Level dependencies awards the badge to users with ANY level in the specified projects as opposed to users who meet the level requirements.

To reproduce:
1. Create a Global Badge
1. Add a single Project Level dependency (higher than any current user has)
1. Enable the Global Badge
1. check user_achievements - user's with ANY achieved level in the specified project will have been awarded the global badge

**Comment by rmmayo** [comment]
:+1:
