### ISSUE TITLE
Global Badge Details in client-display incorrectly shows all Skills assigned to the Badge for each project

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#867]
All skills from all projects assigned to the Global Badge are incorrectly shown beneath each project in the global badge details view.

To reproduce:
1. Create Global Badge
1. Assign Skill from Project A
1. Assign Skill from Project B
1. View Global Badge in client-display
Note that the Skill from Project B is shown under the Project A section (in addition to Project A's skill) and the Skill from Project A is shown under the Project B section in addition to the Skill from Project B.

**Comment by mosefer** [comment]
PR #870

**Comment by rmmayo** [comment]
:+1:
