### ISSUE TITLE
Error trying to "Preview" a project from the Admin view

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#887]
Preview will cause the error below if the project the user is trying to preview is not in "Production Mode" and also added to that user's projects on the "Progress and Rankings" page.  Admin's should be able to preview without those constraints. 

![image](https://user-images.githubusercontent.com/47030042/137176222-629afb86-957e-4eea-9856-68a64360be2f.png)

**Comment by sudo-may** [comment]
:+1:
