### ISSUE TITLE
Create Skill Catalog to facilitate sharing skills and subjects between projects

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#889]
Create a catalog of shared skills and subjects that can be imported as read-only into other projects. Completion of skill/subject would be reflected across the different projects into which they are imported. This is in addition to and separate from the current cross project dependency capability.

Edits made in the owning project would be reflected across all projects that have imported those skills or subjects. 

There should be a single view available to a project administrator that shows all the skills/subjects that they've shared from their current project, and from which skills/subjects can be unshared/retracted (provide warning that this will impact other projects if in use). 

The subjects and skills views should have an import (from catalog) button that will allow skills/subjects shared to the global catalog to be imported into this project - those items will be read-only and cannot be edited/changed by the non-owning project. There should be a visual indicator that a subject or skills are imported from another project (in the dashboard).

In the owning project, shared subjects or skills should have a visual indicator to indicate that they are shared to the global catalog, that indicator should link to the Sharing view that displays all of the shared skills and subjects in the project.

**Comment by sudo-may** [comment]
work continues via #1098
