### ISSUE TITLE
Show support/contact options

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#919]
- Display how users can contact SkillTree support team (email, chat, etc..)
- Make the information configurable through the dashboard OR system/spring properties
- Make information easily accessible from the dashboard's header
  - optionally enhance current "Question Mark" icon
 - make sure information is available on the login page (form/oath based login) as well as on the unauthorized and error pages

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1021

**Comment by rmmayo** [comment]
The links to chat/email in the footer should open in a new tab the way the links under question mark drop down do.  The footer links replace the current page.
