### ISSUE TITLE
Allow for customizing the display name of `Level` in the Skills Display

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#938]
the word "Level" may be overloaded to some organizations.  Allow a project administrator to customize this to a different name (default will remain "Level") via project settings in the dashboard and then use the value returned in settings through the Skills Display views.

**Comment by rmmayo** [comment]
PR: #951

**Comment by mosefer** [comment]
If a custom level label is configured, it is not reflected on the Progress and Ranking overview card for a Project.

**Comment by rmmayo** [comment]
> If a custom level label is configured, it is not reflected on the Progress and Ranking overview card for a Project.

@cjmoses - created #967 to address this issue
