### ISSUE TITLE
Search and navigate directly to Skill does not support Skills defined as part of a Skill Group

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#954]
Skills defined as part of a Skill Group are not discoverable in the Search and navigate directly to a skill search box

**Comment by sudo-may** [comment]
looks like Group's skills cannot participate in the dependencies since that logic uses the same service call

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/958

**Comment by mosefer** [comment]
:+1:
