### ISSUE TITLE
Skill Filter on subject page of dashboard does not work for group child skills

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#955]
![image](https://user-images.githubusercontent.com/47030042/141797024-0253e19a-c7b9-4ec5-8278-c8f1da96edea.png)

![image](https://user-images.githubusercontent.com/47030042/141797111-6b0ec89b-4e0a-49e9-a616-6ed2b3153451.png)

**Comment by sudo-may** [comment]
dup to #964
