### ISSUE TITLE
Approval request from Self Report skills contained in a Skill Group is not visible in the admin dashboard

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#956]
Self Report Approval Request submitted from a Skill that falls within a Skill Group is not visible/approvable form within the administrator view in the dashboard. The request is created in the database but not returned when loading to-be-approved requests in the Project->Self Report view.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/961

**Comment by mosefer** [comment]
:+1:
