### ISSUE TITLE
Self report honor system skills in Skill Group cause temporary doubling of reported points in display

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#959]
Create a Skill Group with 3 honor system Self Report skills that requires 2 out 3 for completion. Notice that reporting the completion of one of the skills in the group through the client-display results in the incorrect display of the points achieved (2x actual) for that skill event (however the Skill Groups total points is correct). This is only on the client side as refreshing the view results in the correct point metrics.

It also appears that arriving at the Skill Group using the Self Reported Skills filter on the skill search box does not exhibit the above doubling, however browsing directly to the Skill Group or using the text input for the skill search box does result in the doubling of points in the specific skill metrics cards.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/963

**Comment by mosefer** [comment]
This appears to still be an issue in the specific case of arriving at the honor system skill in a skill group via filtering on it the name of the skill group (as opposed to scrolling to locate the skill group).

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/972

**Comment by mosefer** [comment]
:+1:
