### ISSUE TITLE
Upgrade VeeValidate to the latest version

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#96]
We are currently on ``2.2.15`` and 3.X+ upgrade will require updating majority of validation, from VeeValidate docs:

```
You should treat 3.x as a different library and read the documentation carefully
```
Here is the guide: 
https://logaretm.github.io/vee-validate/migration.html#migrating-from-2-x-to-3-0

Add cypress tests for validation

**Comment by mosefer** [comment]
This ticket needs to wait on the resolution of #110, tests can't be fixed until the broken Icon Selector is fixed.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/119
