### ISSUE TITLE
Skill filter/search on the subject page does not find skills declared under a group

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#964]

**Comment by sudo-may** [comment]
after further evaluation this is too large of a change; in this ticket will just improve the filter label and add the item to the backlog (https://github.com/NationalSecurityAgency/skills-service/issues/996)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/997

**Comment by mosefer** [comment]
:+1:
