### ISSUE TITLE
We need to replace vue-table-2 with another library 

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#97]
As of version 1.6.0, vue-table-2  is licensed under the GPLv3 license.

Replacement candidates:
- [vue-bootstrap Table Component](https://bootstrap-vue.org/docs/components/table)
   - already have it as dependency so also could be a win in reducing the bundle size

Decided to go with vue-bootstrap, going to break it down to 1 ticket per table and user this ticket to track progress: 
- Levels Page Table: https://github.com/NationalSecurityAgency/skills-service/issues/238 :thumbsup:
- Users Page Table: https://github.com/NationalSecurityAgency/skills-service/issues/249 :thumbsup:
- Access Management Page: https://github.com/NationalSecurityAgency/skills-service/issues/258 :thumbsup:
- Cross-project Skills Page: https://github.com/NationalSecurityAgency/skills-service/issues/266 :thumbsup:
- Skills Page: https://github.com/NationalSecurityAgency/skills-service/issues/278 :thumbsup:
- Performed Skills Page: https://github.com/NationalSecurityAgency/skills-service/issues/288 :thumbsup:
- SimpleSkillsTable Component: https://github.com/NationalSecurityAgency/skills-service/issues/289 :thumbsup:

**Comment by cassandrabailey293** [comment]
anyone working on this yet/still want this to happen? i may take a stab at it.

**Comment by sudo-may** [comment]
Hi @cassandrabailey293, it's great to hear from you! There is actually already a generic table component which is using vue-bootstrap on t#95/metrics branch (#95). That table component is supporting improved metrics implementation but I was also thinking would replace vue-table-2 as well. 

If you are interested in contributing to SkillTree right away I just created number of low(ish) hanging fruit tickets - https://github.com/NationalSecurityAgency/skills-service/labels/good%20first%20issue

If you are specifically interested in this ticket I can let you know once the #95 is complete and t#95/metrics branch is merged.
