### ISSUE TITLE
Minor visual improvements

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#973]
- make ``Search and navigate directly to skill`` more prominent so it doesn't blend into the page
- Rename "Production Mode" setting to ``Discoverable``
- On the Dashboard footer add html title to the version indicating build date

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/974

**Comment by mosefer** [comment]
:+1:
