### ISSUE TITLE
Group's date-based sorting is not respected when group goes live

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#976]
To replicate: 
- create few skills
- great group and add few skills to that group
- click 'Go Live' and the group is pushed to the bottom even though it was the first item

** refresh fixes the issue **

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/977

**Comment by mosefer** [comment]
:+1:
