### ISSUE TITLE
"Go Live" button enabled with only one child skill in skills group

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#983]
create a skill group, add a single child skill to the group, go live button is enabled (but should not be), if you click it you get the error page

**Comment by sudo-may** [comment]
also fixing the issue where self reported skills within a group required for a group to have at least 100 points before they event is accepted (regardless of the subjects or projects total points)

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/986

**Comment by jdbaudean** [comment]
Both issues are fixed in dev-pki and dev-oauth
