### ISSUE TITLE
Improve how external links display within markdown (both Skills Display and Dashboard)

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#987]
inks blend into the text, for example:

![image](https://user-images.githubusercontent.com/51749745/143111035-a3bbf98c-9909-4f43-bd76-293bac6926e1.png)

probably should underline?

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/988

**Comment by mosefer** [comment]
:+1:
