### ISSUE TITLE
Subject and Skill Users Total Points column value incorrect

### ISSUE THREAD

**Issue by mosefer** [NationalSecurityAgency/skills-service#989]
The Users table for both Skill and Subject presents a wildly inaccurate Total Points value - Subject total points for a user are several multiples higher than the total project points for the same user. This does not appear to impact the points displayed for a user in the client-display view and seems limited in scope to the Skill Users and Subject Users views.

```UserPointsRepo.findDistinctProjectUsersByProjectIdAndSkillIdInAndUserIdLike``` looks to be the culprit.

**Comment by mosefer** [comment]
PR #993

**Comment by rmmayo** [comment]
:+1:
