### ISSUE TITLE
Give direct instruction to how create a first project

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#990]
Current view is a bit bare: 

![image](https://user-images.githubusercontent.com/51749745/144160824-93fac595-67c5-41e1-8cea-be1d714d08ba.png)

- Add this description, maybe: ``A Project is an overall container that represents the skills ruleset for a single application with gamified training. Project's administrator(s) manage skill definitions, subjects, levels, dependencies and other attributes that make up an application's training profile.``
- Add instruction to how to create a new project.

**Comment by rmmayo** [comment]
:+1:
