### ISSUE TITLE
help url validation improvement

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#998]
currently, if the help URL for a skill is added with a leading slash (`/`), there is a validation error.

This happens a "root help url" is specificed or not:

![image](https://user-images.githubusercontent.com/47030042/144461032-8724f6e0-23fb-467b-8776-95cfff39ebe5.png)
![image](https://user-images.githubusercontent.com/47030042/144461089-963dc274-7644-4a81-85bc-b928bf80c776.png)

We should either add the leading slash if not present (and not http/https), or change the error message to something like: "...must start with "/" or http/https"

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1002

**Comment by rmmayo** [comment]
root url allows you to put in an invalid url, and if you do and then use it in a skill it will cause an error:

![image](https://user-images.githubusercontent.com/47030042/144897745-a36bf117-8335-4ffd-b278-dac9d68d5d64.png)

**Comment by rmmayo** [comment]
created a separate ticket for validating the help url: https://github.com/NationalSecurityAgency/skills-service/issues/1007
