### ISSUE TITLE
Changing # of skills required for skill group requires syncing even though all child skills have the same total point value

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#999]
Create a group, add 2 child skills, 100 points each, then add a 3rd with only 50 points. Go to change the number of skills required from ALL SKILLS to 2 skills, and dialog says you need to sync points (which is correct). Instead of syncing, edit child 3 and change its points to 100.   If you then go back and try to change the number of skills required back to 2, it still says you need to sync (even though all child skills have the same total # of points).

Note, If you reload it recognizes that all skills have the same total point value and does not require sync'ing.

**Comment by rmmayo** [comment]
this bug also occurs  when creating  a new group, and all skills are given the same # of total points initially.

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1006

**Comment by rmmayo** [comment]
:+1:
